package Matematica.Intermediario.Pitagoras.Nivel3Package;

import java.util.Random;

public class TextoPitagoras
{
	static ProblemaPitagoras  problemas[]= {
		new ProblemaPitagoras("Em um triângulo retângulo, a base mede $b cm e a altura mede $c cm. Qual a hipotenusa?", TipoPitagoras.XBC),
		new ProblemaPitagoras("Um triângulo retângulo tem base de $b m e altura de $c m. Determine a medida da hipotenusa.", TipoPitagoras.XBC),
		new ProblemaPitagoras("Calcule a hipotenusa de um triângulo retângulo com base $b e altura $c.", TipoPitagoras.XBC),
		new ProblemaPitagoras("Em um triângulo retângulo, os catetos medem $b e $c. Encontre a hipotenusa.", TipoPitagoras.XBC),
		new ProblemaPitagoras("Dado um triângulo retângulo com lados $b e $c, ache a hipotenusa.", TipoPitagoras.XBC),
		new ProblemaPitagoras("A base de um triângulo retângulo é $b e a altura é $c. Qual é a hipotenusa?", TipoPitagoras.XBC),
		new ProblemaPitagoras("Triângulo retângulo com cateto maior $b e menor $c. Calcule a hipotenusa.", TipoPitagoras.XBC),
		new ProblemaPitagoras("Determine a hipotenusa de um triângulo retângulo cujos catetos são $b e $c.", TipoPitagoras.XBC),
		new ProblemaPitagoras("Um triângulo retângulo tem lados $b e $c. Qual o valor da hipotenusa?", TipoPitagoras.XBC),
		new ProblemaPitagoras("Num triângulo retângulo, $b é a base e $c a altura. Descubra a hipotenusa.", TipoPitagoras.XBC),
		new ProblemaPitagoras("No triângulo retângulo, temos $b e $c como catetos. Achar a hipotenusa.", TipoPitagoras.XBC),
		new ProblemaPitagoras("Um triângulo retângulo tem catetos medindo $b e $c. Encontre a hipotenusa.", TipoPitagoras.XBC),
		new ProblemaPitagoras("No triângulo retângulo, calcule a hipotenusa sabendo que os catetos são $b e $c.", TipoPitagoras.XBC),
		new ProblemaPitagoras("Calcule a hipotenusa em um triângulo retângulo com catetos $b e $c.", TipoPitagoras.XBC),
		new ProblemaPitagoras("Em um triângulo retângulo com catetos $b e $c, qual o comprimento da hipotenusa?", TipoPitagoras.XBC),
		new ProblemaPitagoras("Determine a diagonal de um retângulo com lados $b e $c?", TipoPitagoras.XBC),
		new ProblemaPitagoras("Qual a hipotenusa de um triângulo retângulo com base $b e altura $c?", TipoPitagoras.XBC),
		new ProblemaPitagoras("A hipotenusa de um triângulo retângulo tem catetos de $b e $c. Calcule-a.", TipoPitagoras.XBC),
		new ProblemaPitagoras("Dados os catetos $b e $c de um triângulo retângulo, ache sua hipotenusa.", TipoPitagoras.XBC),
		new ProblemaPitagoras("Triângulo retângulo com base $b e altura $c. Quanto mede a hipotenusa?", TipoPitagoras.XBC),
		new ProblemaPitagoras("Em um triângulo retângulo, $b é a base, $c é a altura. Qual a hipotenusa?", TipoPitagoras.XBC),
		new ProblemaPitagoras("Considere um triângulo retângulo com lados $b e $c. Determine a hipotenusa.", TipoPitagoras.XBC),
		new ProblemaPitagoras("Calcule a hipotenusa de um triângulo retângulo onde os catetos são $b e $c.", TipoPitagoras.XBC),
		new ProblemaPitagoras("Qual o valor da hipotenusa em um triângulo retângulo de catetos $b e $c?", TipoPitagoras.XBC),
		new ProblemaPitagoras("Dado um triângulo retângulo com catetos de $b cm e $c cm, calcule a hipotenusa.", TipoPitagoras.XBC),
		new ProblemaPitagoras("Ache a hipotenusa de um triângulo retângulo com lados $b e $c.", TipoPitagoras.XBC),
		new ProblemaPitagoras("Determine a hipotenusa de um triângulo retângulo com catetos $b e $c.", TipoPitagoras.XBC),
		new ProblemaPitagoras("Triângulo retângulo com catetos $b e $c. Encontre o comprimento da hipotenusa.", TipoPitagoras.XBC),
		new ProblemaPitagoras("Calcule a hipotenusa de um triângulo retângulo em que os lados são $b e $c.", TipoPitagoras.XBC),
		new ProblemaPitagoras("Triângulo retângulo tem lados $b e $c. Qual é a medida da hipotenusa?", TipoPitagoras.XBC),


		new ProblemaPitagoras("Em um triângulo retângulo, a hipotenusa mede $a e a altura $c. Qual a base?", TipoPitagoras.AXC),
		new ProblemaPitagoras("Triângulo retângulo com hipotenusa $a e altura $c. Determine o cateto maior.", TipoPitagoras.AXC),
		new ProblemaPitagoras("No triângulo retângulo, a hipotenusa é $a e o cateto menor $c. Encontre a base.", TipoPitagoras.AXC),
		new ProblemaPitagoras("Em um triângulo retângulo, sabendo que a hipotenusa é $a e a altura $c, qual é o cateto maior?", TipoPitagoras.AXC),
		new ProblemaPitagoras("A hipotenusa vale $a e o cateto menor $c. Descubra a base do triângulo retângulo.", TipoPitagoras.AXC),
		new ProblemaPitagoras("Com hipotenusa $a e altura $c, calcule a base do triângulo retângulo.", TipoPitagoras.AXC),
		new ProblemaPitagoras("Em um triângulo retângulo, a hipotenusa é $a e a altura $c. Ache o cateto maior.", TipoPitagoras.AXC),
		new ProblemaPitagoras("Hipotenusa de $a e altura de $c. Qual o valor do cateto maior no triângulo retângulo?", TipoPitagoras.AXC),
		new ProblemaPitagoras("Dado um triângulo retângulo com lados $a e $c. Calcule o cateto maior.", TipoPitagoras.AXC),
		new ProblemaPitagoras("A hipotenusa de um triângulo retângulo mede $a e o cateto menor $c. Qual a base?", TipoPitagoras.AXC),
		new ProblemaPitagoras("Determine o cateto maior em um triângulo retângulo com hipotenusa $a e altura $c.", TipoPitagoras.AXC),
		new ProblemaPitagoras("No triângulo retângulo, os lados são $a e $c. Qual o valor do cateto maior?", TipoPitagoras.AXC),
		new ProblemaPitagoras("Triângulo retângulo com hipotenusa $a e altura $c. Encontre a base.", TipoPitagoras.AXC),
		new ProblemaPitagoras("Em um triângulo retângulo, a hipotenusa mede $a e o cateto menor $c. Quanto mede a base?", TipoPitagoras.AXC),
		new ProblemaPitagoras("Calcule o cateto maior de um triângulo retângulo com lados $a e $c.", TipoPitagoras.AXC),
		new ProblemaPitagoras("Qual é o comprimento da base de um triângulo retângulo com hipotenusa $a e altura $c?", TipoPitagoras.AXC),
		new ProblemaPitagoras("Em um triângulo retângulo com hipotenusa $a e altura $c, qual é a medida do cateto maior?", TipoPitagoras.AXC),
		new ProblemaPitagoras("Triângulo retângulo com hipotenusa $a e cateto menor $c. Determine a base.", TipoPitagoras.AXC),
		new ProblemaPitagoras("Se a hipotenusa é $a e a altura é $c, calcule o cateto maior do triângulo retângulo.", TipoPitagoras.AXC),
		new ProblemaPitagoras("Em um triângulo retângulo com $a de hipotenusa e $c de altura, ache a base.", TipoPitagoras.AXC),
		new ProblemaPitagoras("Determine a base do triângulo retângulo com hipotenusa $a e altura $c.", TipoPitagoras.AXC),
		new ProblemaPitagoras("Dado um triângulo retângulo com hipotenusa $a e altura $c. Qual o cateto maior?", TipoPitagoras.AXC),
		new ProblemaPitagoras("Em um triângulo retângulo, se a hipotenusa for $a e a altura $c, quanto mede o cateto maior?", TipoPitagoras.AXC),
		new ProblemaPitagoras("Triângulo retângulo com hipotenusa $a e cateto menor $c. Ache a base.", TipoPitagoras.AXC),
		new ProblemaPitagoras("Calcule o cateto maior do triângulo retângulo com lados $a e $c.", TipoPitagoras.AXC),
		new ProblemaPitagoras("Em um triângulo retângulo, a hipotenusa é $a e o cateto menor $c. Determine o outro cateto (base).", TipoPitagoras.AXC),
		new ProblemaPitagoras("Hipotenusa $a e altura $c. Qual o comprimento da base do triângulo retângulo?", TipoPitagoras.AXC),
		new ProblemaPitagoras("Descubra o valor da base de um triângulo retângulo com hipotenusa $a e altura $c.", TipoPitagoras.AXC),
		new ProblemaPitagoras("Triângulo retângulo: hipotenusa $a, altura $c. Calcule o cateto maior.", TipoPitagoras.AXC),


			
		new ProblemaPitagoras("Em um triângulo retângulo, a hipotenusa mede $a e a base $b. Qual é a altura?", TipoPitagoras.ABX),
		new ProblemaPitagoras("Dado um triângulo retângulo com hipotenusa $a e base $b, calcule a altura.", TipoPitagoras.ABX),
		new ProblemaPitagoras("A hipotenusa é $a e o cateto maior $b. Quanto vale o cateto menor?", TipoPitagoras.ABX),
		new ProblemaPitagoras("Num triângulo retângulo, a base é $b e a hipotenusa $a. Ache a altura.", TipoPitagoras.ABX),
		new ProblemaPitagoras("Triângulo retângulo com hipotenusa $a e base $b. Determine a altura.", TipoPitagoras.ABX),
		new ProblemaPitagoras("Qual é a altura do triângulo retângulo se a hipotenusa vale $a e a base $b?", TipoPitagoras.ABX),
		new ProblemaPitagoras("Em um triângulo retângulo, a hipotenusa mede $a e a base $b. Qual é a medida do cateto menor?", TipoPitagoras.ABX),
		new ProblemaPitagoras("Sabendo que a hipotenusa é $a e a base $b, descubra a altura do triângulo retângulo.", TipoPitagoras.ABX),
		new ProblemaPitagoras("Calcule o cateto menor de um triângulo retângulo com hipotenusa $a e base $b.", TipoPitagoras.ABX),
		new ProblemaPitagoras("Com base $b e hipotenusa $a em um triângulo retângulo, encontre a altura.", TipoPitagoras.ABX),
		new ProblemaPitagoras("Determine a altura no triângulo retângulo com hipotenusa $a e base $b.", TipoPitagoras.ABX),
		new ProblemaPitagoras("Triângulo retângulo: hipotenusa $a, base $b. Qual o valor da altura?", TipoPitagoras.ABX),
		new ProblemaPitagoras("Em um triângulo retângulo, se a hipotenusa mede $a e o cateto maior $b, qual o comprimento da altura?", TipoPitagoras.ABX),
		new ProblemaPitagoras("A hipotenusa é $a e o cateto maior é $b. Calcule o outro cateto do triângulo retângulo.", TipoPitagoras.ABX),
		new ProblemaPitagoras("Qual é o cateto menor de um triângulo retângulo com base $b e hipotenusa $a?", TipoPitagoras.ABX),
		new ProblemaPitagoras("Triângulo retângulo com lados $a e $b. Qual o valor do cateto menor?", TipoPitagoras.ABX),
		new ProblemaPitagoras("Em um triângulo retângulo, conhecendo a hipotenusa $a e a base $b, calcule a altura.", TipoPitagoras.ABX),
		new ProblemaPitagoras("Descubra a altura de um triângulo retângulo com hipotenusa $a e cateto maior $b.", TipoPitagoras.ABX),
		new ProblemaPitagoras("Base $b e hipotenusa $a são lados de um triângulo retângulo. Ache a altura.", TipoPitagoras.ABX),
		new ProblemaPitagoras("No triângulo retângulo com base $b e hipotenusa $a, quanto vale o cateto menor?", TipoPitagoras.ABX),
		new ProblemaPitagoras("Um triângulo retângulo tem hipotenusa $a e base $b. Determine o outro cateto.", TipoPitagoras.ABX),
		new ProblemaPitagoras("Hipotenusa $a e cateto maior $b. Qual o comprimento da altura no triângulo retângulo?", TipoPitagoras.ABX),
		new ProblemaPitagoras("Dado um triângulo retângulo com lados $a e $b, encontre o cateto menor.", TipoPitagoras.ABX),
		new ProblemaPitagoras("Em um triângulo retângulo, a hipotenusa é $a e a base $b. Qual é a altura?", TipoPitagoras.ABX),
		new ProblemaPitagoras("A hipotenusa de um triângulo retângulo vale $a e a base $b. Quanto mede a altura?", TipoPitagoras.ABX),
		new ProblemaPitagoras("Triângulo retângulo com cateto maior $b e hipotenusa $a. Ache o cateto menor.", TipoPitagoras.ABX),
		new ProblemaPitagoras("Calcule o outro cateto no triângulo retângulo com hipotenusa $a e base $b.", TipoPitagoras.ABX),
		new ProblemaPitagoras("No triângulo retângulo, temos hipotenusa $a e base $b. Qual o cateto menor?", TipoPitagoras.ABX),
		new ProblemaPitagoras("Base $b e hipotenusa $a formam um triângulo retângulo. Calcule a altura.", TipoPitagoras.ABX),
		new ProblemaPitagoras("Dado um triângulo retângulo com hipotenusa $a e cateto maior $b, qual a altura?", TipoPitagoras.ABX),

			
//			new ProblemaPitagoras("Uma escada encostada na parede tem a base $b decímetros da parede e atinge uma altura de $c decímetros. Qual seu comprimento em decímetros?", TipoPitagoras.XBC),
//			new ProblemaPitagoras("Qual o comprimento de uma rampa que sobe $c metros de altura em uma distância horizontal de $b metros?", TipoPitagoras.XBC),
//			new ProblemaPitagoras("Um pintor apoia uma escada na parede, a base está a $b decímetros da parede e a escada alcança $c decímetros de altura. Qual seu comprimento em decímetros?", TipoPitagoras.XBC),
//			new ProblemaPitagoras("Uma pessoa atravessa um terreno andando $b metros para o leste e depois $c metros para o norte. Qual é a distância direta entre os pontos?", TipoPitagoras.XBC),
//			new ProblemaPitagoras("Uma rampa acessível sobe $c metros de altura em um percurso horizontal de $b metros. Qual é o comprimento da rampa?", TipoPitagoras.XBC),
//			new ProblemaPitagoras("Uma escada de incêndio está encostada em um prédio. A base está a $b metros da parede e a altura é $c metros. Qual o comprimento da escada?", TipoPitagoras.XBC),
//			new ProblemaPitagoras("Para atravessar um rio de $b metros de largura e depois subir um barranco de $c metros, qual é a distância direta até o topo?", TipoPitagoras.XBC),
//			new ProblemaPitagoras("Um cabo liga o topo de uma antena de $c metros de altura a um ponto no solo distante $b metros da base. Qual o comprimento do cabo?", TipoPitagoras.XBC),
//			new ProblemaPitagoras("Um operário constrói uma rampa que sobe $c metros em um percurso horizontal de $b metros. Qual será o comprimento da rampa?", TipoPitagoras.XBC),
//			new ProblemaPitagoras("Uma ponte pênsil tem cabos inclinados que ligam torres de $c metros de altura a pontos no chão a $b metros de distância. Qual é o comprimento do cabo?", TipoPitagoras.XBC),
//			new ProblemaPitagoras("Uma escada está apoiada em uma árvore, com a base a $b decímetros do tronco e alcança $c decímetros de altura. Qual o comprimento da escada em decímetros?", TipoPitagoras.XBC),
//			new ProblemaPitagoras("Um trabalhador sobe uma rampa que sobe $c metros em uma distância horizontal de $b metros. Qual é o comprimento da rampa?", TipoPitagoras.XBC),
//			new ProblemaPitagoras("Uma tirolesa parte de um ponto no topo de uma torre de $c metros de altura até um ponto no chão a $b metros de distância. Qual o comprimento do cabo?", TipoPitagoras.XBC),
//			new ProblemaPitagoras("Uma corda esticada vai do topo de um mastro de $c metros até um ponto no solo a $b metros de distância. Qual é seu comprimento?", TipoPitagoras.XBC),
//			new ProblemaPitagoras("Um eletricista precisa instalar um fio que vai do topo de um poste de $c metros até um ponto no solo distante $b metros. Qual o comprimento do fio?", TipoPitagoras.XBC),
//			new ProblemaPitagoras("Um engenheiro desenha uma rampa que sobe $c metros de altura em $b metros na horizontal. Qual será o comprimento total da rampa?", TipoPitagoras.XBC),
//			new ProblemaPitagoras("Uma escada está encostada em um muro. A base está a $b decímetros do muro e ela alcança $c decímetros de altura. Qual é o comprimento da escada em decímetros?", TipoPitagoras.XBC),
//			new ProblemaPitagoras("Um trilho diagonal conecta dois andares separados por $c metros de altura e $b metros na horizontal. Qual é o comprimento do trilho?", TipoPitagoras.XBC),
//			new ProblemaPitagoras("Uma passarela elevada liga dois prédios, com uma diferença de altura de $c metros e distância horizontal de $b metros. Qual seu comprimento?", TipoPitagoras.XBC),
//			new ProblemaPitagoras("Para puxar uma carga até o topo de uma rampa com $c metros de altura e $b metros de base, qual deve ser o comprimento do cabo?", TipoPitagoras.XBC),
//			new ProblemaPitagoras("Um caminhão descarrega materiais usando uma esteira que sobe $c metros em um deslocamento horizontal de $b metros. Qual é o comprimento da esteira?", TipoPitagoras.XBC),
//			new ProblemaPitagoras("Uma ponte em diagonal liga dois pontos separados por $b metros na horizontal e $c metros na vertical. Qual o comprimento da ponte?", TipoPitagoras.XBC),
//			new ProblemaPitagoras("Um funicular sobe uma montanha ganhando $c metros de altura para cada $b metros de deslocamento horizontal. Qual é o comprimento da linha?", TipoPitagoras.XBC),
//			new ProblemaPitagoras("Uma pessoa atravessa uma praça caminhando $b metros para frente e depois $c metros para o lado. Qual é a distância direta até o destino?", TipoPitagoras.XBC),
//			new ProblemaPitagoras("Uma linha de energia vai do topo de um prédio de $c metros até um ponto no solo a $b metros de distância. Qual o comprimento do fio?", TipoPitagoras.XBC),
//			new ProblemaPitagoras("Uma rampa de acesso permite vencer uma altura de $c metros com um deslocamento de $b metros na horizontal. Qual é o comprimento da rampa?", TipoPitagoras.XBC),
//		
//			new ProblemaPitagoras("Uma escada de $a metros alcança uma altura de $c metros. Qual a distância da base da escada até a parede?", TipoPitagoras.AXC),
//			new ProblemaPitagoras("Uma rampa tem comprimento de $a metros e sobe até $c metros de altura. Qual é a base horizontal da rampa?", TipoPitagoras.AXC),
//			new ProblemaPitagoras("Um fio de $a metros sustenta um poste de $c metros. Qual é a distância do poste até o ponto onde o fio toca o solo?", TipoPitagoras.AXC),
//			new ProblemaPitagoras("Um cabo de $a metros vai do topo de uma torre de $c metros até o chão. Qual é a distância da base da torre até o ponto do cabo?", TipoPitagoras.AXC),
//			new ProblemaPitagoras("Uma escada está apoiada no muro com comprimento de $a metros e alcança $c metros de altura. Qual é a distância da base até o muro?", TipoPitagoras.AXC),
//			new ProblemaPitagoras("Uma rampa de $a metros permite subir $c metros de altura. Qual é a extensão da base da rampa?", TipoPitagoras.AXC),
//			new ProblemaPitagoras("Um fio liga o topo de uma antena de $c metros até um ponto no chão distante, usando um cabo de $a metros. Qual a distância horizontal?", TipoPitagoras.AXC),
//			new ProblemaPitagoras("Uma escada de $a metros alcança uma janela a $c metros de altura. Qual é a distância da base da escada até a parede?", TipoPitagoras.AXC),
//			new ProblemaPitagoras("Um operário monta uma rampa de $a metros que sobe até $c metros. Qual é a medida da base da rampa?", TipoPitagoras.AXC),
//			new ProblemaPitagoras("Um trilho de $a metros liga dois pontos com diferença de altura de $c metros. Qual é a distância horizontal entre eles?", TipoPitagoras.AXC),
//			new ProblemaPitagoras("Um funicular sobe uma montanha com $c metros de altura, usando uma linha de $a metros. Qual é o comprimento da base?", TipoPitagoras.AXC),
//			new ProblemaPitagoras("Uma tirolesa parte de uma torre de $c metros, com cabo de $a metros até o solo. Qual é a distância horizontal até o ponto de chegada?", TipoPitagoras.AXC),
//			new ProblemaPitagoras("Uma passarela inclinada tem comprimento de $a metros e sobe $c metros de altura. Qual é o comprimento da base?", TipoPitagoras.AXC),
//			new ProblemaPitagoras("Uma ponte pênsil tem cabos de $a metros que sobem até torres de $c metros. Qual é a distância da base dos cabos até a torre?", TipoPitagoras.AXC),
//			new ProblemaPitagoras("Uma escada de incêndio tem comprimento de $a metros e sobe até $c metros de altura. Qual a distância da base da escada até a parede?", TipoPitagoras.AXC),
//			new ProblemaPitagoras("Um eletricista puxa um fio de $a metros desde o topo de um poste de $c metros. Qual é a distância da base até o ponto no chão?", TipoPitagoras.AXC),
//			new ProblemaPitagoras("Uma escada de $a metros sobe até $c metros de altura em uma obra. Qual a distância da base da escada até a parede?", TipoPitagoras.AXC),
//			new ProblemaPitagoras("Um trilho diagonal de $a metros conecta dois níveis separados por $c metros. Qual é a extensão da base horizontal?", TipoPitagoras.AXC),
//			new ProblemaPitagoras("Uma linha de transmissão de $a metros liga o topo de uma torre de $c metros até um ponto no chão. Qual é a distância horizontal?", TipoPitagoras.AXC),
//			new ProblemaPitagoras("Um cabo de $a metros conecta o topo de um prédio de $c metros até um ponto no solo. Qual é a distância horizontal da base?", TipoPitagoras.AXC),
//			new ProblemaPitagoras("Uma escada de $a metros encosta em uma árvore e alcança $c metros de altura. Qual é a distância da base até a árvore?", TipoPitagoras.AXC),
//			new ProblemaPitagoras("Uma esteira transportadora de $a metros sobe até $c metros de altura. Qual é a extensão da base da esteira?", TipoPitagoras.AXC),
//			new ProblemaPitagoras("Uma ponte inclinada de $a metros sobe até $c metros. Qual é a distância da base até o topo da ponte?", TipoPitagoras.AXC),
//			new ProblemaPitagoras("Uma rampa de acesso tem comprimento de $a metros e sobe até $c metros. Qual é o comprimento da base da rampa?", TipoPitagoras.AXC),
//			new ProblemaPitagoras("Uma linha de segurança sai do topo de uma estrutura de $c metros e mede $a metros. Qual é a distância da base ao ponto de fixação no solo?", TipoPitagoras.AXC),
//			new ProblemaPitagoras("Uma escada de $a metros sobe até $c metros de altura em uma parede. Qual é a distância horizontal da base da escada até a parede?", TipoPitagoras.AXC),
//			new ProblemaPitagoras("Uma tirolesa de $a metros parte de uma torre de $c metros até o solo. Qual é a distância horizontal da base?", TipoPitagoras.AXC),
//			new ProblemaPitagoras("Uma rampa inclinada tem comprimento de $a metros e sobe até $c metros. Qual é a extensão da base horizontal?", TipoPitagoras.AXC),
//			new ProblemaPitagoras("Um trabalhador puxa uma corda de $a metros do topo de um galpão de $c metros até o solo. Qual é a distância horizontal até a base?", TipoPitagoras.AXC),
//			new ProblemaPitagoras("Uma passarela tem $a metros de comprimento e sobe até $c metros. Qual é a distância da base da passarela até o início da subida?", TipoPitagoras.AXC),

	
	};
	
	public static ProblemaPitagoras getProblema()
	{
		Random rand=new Random();
		int index=rand.nextInt(problemas.length);
		return problemas[index].clone();
	}
	
}
