package matematica.basico.conjuntos.nivel3package;

import java.util.Random;

public class TextoOperacoesMenos
{
	static OperacoesMenos  problemas[]= {
		
		new OperacoesMenos("Em uma escola, $a alunos gostam de futebol e $i desses alunos gostam de futebol e vôlei. Quantos só gostam de futebol?", "alunos que gostam de futebol", "alunos que gostam de vôlei", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("Uma pesquisa mostra que $a pessoas assistem TV e $i dessas pessoas assistem TV e internet. Quantas assistem só TV?", "pessoas que assistem TV", "pessoas que assistem internet", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("Em um grupo, $a membros falam inglês e $i desses membros falam inglês e francês. Quantos falam só inglês?", "membros que falam inglês", "membros que falam francês", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("No clube, $a atletas correm e $i desses atletas correm e nadam. Quantos correm, mas não nadam?", "atletas que correm", "atletas que nadam", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("Em uma biblioteca, $a livros são de ficção e $i são de ficção e aventura. Quantos são só de ficção?", "livros de ficção", "livros de aventura", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("No evento, $a pessoas jogam xadrez e $i jogam xadrez e damas. Quantos jogam só xadrez?", "pessoas que jogam xadrez", "pessoas que jogam damas", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("Em uma festa, $a convidados gostam de sushi e $i gostam de sushi e pizza. Quantos gostam só de sushi?", "convidados que gostam de sushi", "convidados que gostam de pizza", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("Na academia, $a alunos praticam yoga e $i praticam yoga e pilates. Quantos praticam só yoga?", "alunos que praticam yoga", "alunos que praticam pilates", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("No colégio, $a estudantes leem jornal e $i leem jornal e revistas. Quantos leem só jornal?", "estudantes que leem jornal", "estudantes que leem revistas", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("Em um parque, $a visitantes tiram fotos e $i tiram fotos e filmam. Quantos só tiram fotos?", "visitantes que tiram fotos", "visitantes que filmam", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("Na cidade, $a pessoas usam bicicleta e $i usam bicicleta e transporte público. Quantos usam só bicicleta?", "pessoas que usam bicicleta", "pessoas que usam transporte público", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("Em um curso, $a alunos estudam matemática e $i estudam matemática e física. Quantos estudam só matemática?", "alunos que estudam matemática", "alunos que estudam física", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("No grupo, $a integrantes tocam violão e $i tocam violão e piano. Quantos tocam só violão?", "integrantes que tocam violão", "integrantes que tocam piano", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("Em uma pesquisa, $a pessoas preferem café e $i preferem café e chá. Quantos preferem só café?", "pessoas que preferem café", "pessoas que preferem chá", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("Na feira, $a clientes compram frutas e $i compram frutas e verduras. Quantos compram só frutas?", "clientes que compram frutas", "clientes que compram verduras", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("No time, $a jogadores correm e $i correm e chutam. Quantos correm só?", "jogadores que correm", "jogadores que chutam", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("Na escola, $a alunos participam do coral e $i participam do coral e da banda. Quantos só participam do coral?", "alunos do coral", "alunos da banda", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("Em um sítio, $a pessoas colhem frutas e $i colhem frutas e legumes. Quantos colhem só frutas?", "pessoas que colhem frutas", "pessoas que colhem legumes", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("No clube, $a sócios nadam e $i nadam e jogam tênis. Quantos só nadam?", "sócios que nadam", "sócios que jogam tênis", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("Na pesquisa, $a entrevistados usam internet e $i usam internet e TV a cabo. Quantos usam só internet?", "entrevistados que usam internet", "entrevistados que usam TV a cabo", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("Em um condomínio, $a moradores têm cachorro e $i têm cachorro e gato. Quantos têm só cachorro?", "moradores com cachorro", "moradores com gato", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("No grupo, $a pessoas gostam de rock e $i gostam de rock e pop. Quantos gostam só de rock?", "pessoas que gostam de rock", "pessoas que gostam de pop", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("Em um evento, $a participantes jogam basquete e $i jogam basquete e vôlei. Quantos jogam só basquete?", "participantes que jogam basquete", "participantes que jogam vôlei", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("No bairro, $a moradores reciclam e $i reciclam e compostam lixo. Quantos reciclam só?", "moradores que reciclam", "moradores que compostam", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("Em uma sala, $a alunos gostam de matemática e $i gostam de matemática e física. Quantos só gostam de matemática?", "alunos que gostam de matemática", "alunos que gostam de física", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("No time, $a atletas correm e $i correm e saltam. Quantos correm só?", "atletas que correm", "atletas que saltam", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("Na escola, $a alunos gostam de história e $i gostam de história e geografia. Quantos só gostam de história?", "alunos que gostam de história", "alunos que gostam de geografia", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("Em uma aula, $a estudantes usam laptop e $i usam laptop e tablet. Quantos usam só laptop?", "estudantes que usam laptop", "estudantes que usam tablet", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("No parque, $a visitantes correm e $i correm e caminham. Quantos correm só?", "visitantes que correm", "visitantes que caminham", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("Na escola, $a alunos participam do teatro e $i participam do teatro e da dança. Quantos só participam do teatro?", "alunos do teatro", "alunos da dança", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("Em uma empresa, $a funcionários usam Windows e $i usam Windows e Linux. Quantos usam só Windows?", "funcionários que usam Windows", "funcionários que usam Linux", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("No clube, $a sócios jogam tênis e $i jogam tênis e golfe. Quantos jogam só tênis?", "sócios que jogam tênis", "sócios que jogam golfe", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("Em uma escola, $a alunos leem livros e $i leem livros e jornais. Quantos só leem livros?", "alunos que leem livros", "alunos que leem jornais", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("No time, $a jogadores chutam e $i chutam e correm. Quantos chutam só?", "jogadores que chutam", "jogadores que correm", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("Em uma pesquisa, $a pessoas usam Android e $i usam Android e iOS. Quantos usam só Android?", "pessoas que usam Android", "pessoas que usam iOS", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("No evento, $a pessoas gostam de jazz e $i gostam de jazz e blues. Quantos gostam só de jazz?", "pessoas que gostam de jazz", "pessoas que gostam de blues", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("Na academia, $a alunos levantam peso e $i levantam peso e correm. Quantos só levantam peso?", "alunos que levantam peso", "alunos que correm", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("Em uma pesquisa, $a pessoas usam Facebook e $i usam Facebook e Instagram. Quantos usam só Facebook?", "pessoas que usam Facebook", "pessoas que usam Instagram", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("No condomínio, $a moradores possuem carro e $i possuem carro e moto. Quantos têm só carro?", "moradores que possuem carro", "moradores que possuem moto", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("Em um grupo, $a pessoas falam espanhol e $i falam espanhol e inglês. Quantos falam só espanhol?", "pessoas que falam espanhol", "pessoas que falam inglês", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("No time, $a atletas nadam e $i nadam e correm. Quantos nadam só?", "atletas que nadam", "atletas que correm", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("Em um parque, $a visitantes comem sorvete e $i comem sorvete e pipoca. Quantos comem só sorvete?", "visitantes que comem sorvete", "visitantes que comem pipoca", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("Na escola, $a alunos gostam de química e $i gostam de química e biologia. Quantos só gostam de química?", "alunos que gostam de química", "alunos que gostam de biologia", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("No grupo, $a membros participam de reuniões e $i participam de reuniões e treinamentos. Quantos só participam de reuniões?", "membros que participam de reuniões", "membros que participam de treinamentos", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("Em uma empresa, $a funcionários falam francês e $i falam francês e inglês. Quantos falam só francês?", "funcionários que falam francês", "funcionários que falam inglês", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("No clube, $a sócios jogam golfe e $i jogam golfe e tênis. Quantos jogam só golfe?", "sócios que jogam golfe", "sócios que jogam tênis", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("Em uma pesquisa, $a pessoas preferem suco e $i preferem suco e água. Quantos preferem só suco?", "pessoas que preferem suco", "pessoas que preferem água", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("Na feira, $a clientes compram legumes e $i compram legumes e frutas. Quantos compram só legumes?", "clientes que compram legumes", "clientes que compram frutas", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("No grupo, $a pessoas gostam de filmes de ação e $i gostam de ação e comédia. Quantos gostam só de ação?", "pessoas que gostam de ação", "pessoas que gostam de comédia", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("Em um evento, $a participantes falam português e $i falam português e inglês. Quantos falam só português?", "participantes que falam português", "participantes que falam inglês", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("No bairro, $a moradores têm jardim e $i têm jardim e piscina. Quantos têm só jardim?", "moradores com jardim", "moradores com piscina", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("Na escola, $a alunos praticam futebol e $i praticam futebol e basquete. Quantos praticam só futebol?", "alunos que praticam futebol", "alunos que praticam basquete", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("Em uma aula, $a estudantes usam caderno e $i usam caderno e laptop. Quantos usam só caderno?", "estudantes que usam caderno", "estudantes que usam laptop", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("No parque, $a visitantes correm e $i correm e pedalam. Quantos correm só?", "visitantes que correm", "visitantes que pedalam", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("Na empresa, $a funcionários usam Mac e $i usam Mac e PC. Quantos usam só Mac?", "funcionários que usam Mac", "funcionários que usam PC", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("Em um curso, $a alunos estudam física e $i estudam física e química. Quantos estudam só física?", "alunos que estudam física", "alunos que estudam química", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("No time, $a jogadores chutam e $i chutam e defendem. Quantos chutam só?", "jogadores que chutam", "jogadores que defendem", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("Em uma pesquisa, $a pessoas usam WhatsApp e $i usam WhatsApp e Telegram. Quantos usam só WhatsApp?", "pessoas que usam WhatsApp", "pessoas que usam Telegram", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("No condomínio, $a moradores têm bicicleta e $i têm bicicleta e skate. Quantos têm só bicicleta?", "moradores com bicicleta", "moradores com skate", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("Em um grupo, $a pessoas falam italiano e $i falam italiano e espanhol. Quantos falam só italiano?", "pessoas que falam italiano", "pessoas que falam espanhol", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("No time, $a atletas correm e $i correm e saltam. Quantos correm só?", "atletas que correm", "atletas que saltam", TipoOperacaoMenos.AMenosB),
		new OperacoesMenos("Em um parque, $a visitantes comem pipoca e $i comem pipoca e sorvete. Quantos comem só pipoca?", "visitantes que comem pipoca", "visitantes que comem sorvete", TipoOperacaoMenos.AMenosB),

		
		new OperacoesMenos("Em uma escola, dos $a alunos que gostam de matemática, $aMb não gostam de física. Quantos gostam de ambas as matérias?", "alunos que gostam de matemática", "alunos que gostam de física", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Num grupo, $a pessoas assistem futebol, sendo que $aMb dessas não assistem basquete. Quantas assistem aos dois esportes?", "pessoas que assistem futebol", "pessoas que assistem basquete", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Em uma empresa, $a funcionários usam computador, e $aMb desses não usam tablet. Quantos utilizam os dois dispositivos?", "funcionários que usam computador", "funcionários que usam tablet", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Num clube, $a membros praticam natação, dos quais $aMb não praticam corrida. Quantos praticam os dois esportes?", "membros que praticam natação", "membros que praticam corrida", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Em uma pesquisa, $a pessoas gostam de café, dessas pessoas $aMb não não gostam de chá. Quantas gostam das duas bebidas?", "pessoas que gostam de café", "pessoas que gostam de chá", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Na faculdade, $a alunos falam inglês, e desses alunos, $aMb não falam espanhol. Quantos falam os dois idiomas?", "alunos que falam inglês", "alunos que falam espanhol", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Em um time, $a jogadores treinam de manhã, mas $aMb desses jogadores não treinam à tarde. Quantos treinam nos dois horários?", "jogadores que treinam de manhã", "jogadores que treinam à tarde", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Num evento, $a convidados gostam de jazz, sendo que $aMb deles não gostam de rock. Quantos apreciam ambos os estilos?", "convidados que gostam de jazz", "convidados que gostam de rock", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Em um grupo, $a pessoas leem jornais, mas $aMb delas não leem revistas. Quantas leem ambos?", "pessoas que leem jornais", "pessoas que leem revistas", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Na escola, $a estudantes praticam futebol, desses estudantes, $aMb não praticam vôlei. Quantos praticam os dois esportes?", "estudantes que praticam futebol", "estudantes que praticam vôlei", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Em uma cidade, $a moradores possuem carro, e $aMb desses moradores não possuem moto. Quantos têm os dois veículos?", "moradores que possuem carro", "moradores que possuem moto", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Num colégio, $a alunos participam do coral, desses alunos, $aMb não participam da banda. Quantos participam dos dois grupos?", "alunos do coral", "alunos da banda", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Em uma loja, $a clientes compram eletrônicos, desses clientes, $aMb não compram móveis. Quantos compram ambos?", "clientes que compram eletrônicos", "clientes que compram móveis", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Na biblioteca, $a pessoas pegam livros de ficção, dessas pessoas $aMb não pegam livros de não-ficção. Quantas pegam os dois tipos?", "pessoas que pegam livros de ficção", "pessoas que pegam livros de não-ficção", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Em um parque, $a visitantes andam de bicicleta, mas $aMb deles não andam de skate. Quantos praticam as duas atividades?", "visitantes que andam de bicicleta", "visitantes que andam de skate", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("No grupo, $a membros estudam física, desses membros, $aMb não estudam química. Quantos estudam ambas as disciplinas?", "membros que estudam física", "membros que estudam química", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Em uma aula, $a alunos usam laptops, desses alunos, $aMb não usam tablets. Quantos utilizam os dois aparelhos?", "alunos que usam laptops", "alunos que usam tablets", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Em um bairro, $a casas têm jardim, dessas casas, $aMb não têm garagem. Quantas casas possuem ambos?", "casas que têm jardim", "casas que têm garagem", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Em um curso, $a alunos gostam de biologia, desses alunos, $aMb não gostam de química. Quantos gostam das duas matérias?", "alunos que gostam de biologia", "alunos que gostam de química", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Em uma escola, $a alunos gostam de matemática, e $aMb deles não gostam de física. Quantos gostam de ambos?", "alunos que gostam de matemática", "alunos que gostam de física", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Num grupo, $a pessoas assistem futebol, sendo que $aMb dessas não assistem basquete. Quantas assistem aos dois esportes?", "pessoas que assistem futebol", "pessoas que assistem basquete", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Em uma empresa, $a funcionários usam computador, e $aMb desses não usam tablet. Quantos utilizam os dois dispositivos?", "funcionários que usam computador", "funcionários que usam tablet", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Num clube, $a membros praticam natação, dos quais $aMb não praticam corrida. Quantos praticam os dois esportes?", "membros que praticam natação", "membros que praticam corrida", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Em uma pesquisa, $a pessoas preferem café, sendo $aMb delas que não preferem chá. Quantas gostam das duas bebidas?", "pessoas que preferem café", "pessoas que preferem chá", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Na faculdade, $a alunos falam inglês, desses alunos, $aMb não falam espanhol. Quantos falam os dois idiomas?", "alunos que falam inglês", "alunos que falam espanhol", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Em um time, $a jogadores treinam de manhã, desses jogadores, $aMb não treinam à tarde. Quantos treinam nos dois horários?", "jogadores que treinam de manhã", "jogadores que treinam à tarde", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Num evento, $a convidados gostam de jazz, sendo que $aMb deles não gostam de rock. Quantos apreciam ambos os estilos?", "convidados que gostam de jazz", "convidados que gostam de rock", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Em um grupo, $a pessoas leem jornais, mas $aMb delas não leem revistas. Quantas leem ambos?", "pessoas que leem jornais", "pessoas que leem revistas", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Na escola, $a estudantes praticam futebol, dos quais $aMb não praticam vôlei. Quantos praticam os dois esportes?", "estudantes que praticam futebol", "estudantes que praticam vôlei", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Em uma cidade, $a moradores possuem carro, desses moradores, $aMb desses não possuem moto. Quantos têm os dois veículos?", "moradores que possuem carro", "moradores que possuem moto", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Num colégio, $a alunos participam do coral, desses alunos, $aMb não participam da banda. Quantos participam dos dois grupos?", "alunos do coral", "alunos da banda", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Em uma loja, $a clientes compram eletrônicos, desses clientes, $aMb  não compram móveis. Quantos compram ambos?", "clientes que compram eletrônicos", "clientes que compram móveis", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Na biblioteca, $a pessoas pegam livros de ficção, das quais $aMb não pegam livros de não-ficção. Quantas pegam os dois tipos?", "pessoas que pegam livros de ficção", "pessoas que pegam livros de não-ficção", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Em um parque, $a visitantes andam de bicicleta, mas $aMb deles não andam de skate. Quantos praticam as duas atividades?", "visitantes que andam de bicicleta", "visitantes que andam de skate", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("No grupo, $a membros estudam física, desses membros, $aMb não estudam química. Quantos estudam ambas as disciplinas?", "membros que estudam física", "membros que estudam química", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Em uma aula, $a alunos usam laptops, desses alunos, $aMb não usam tablets. Quantos utilizam os dois aparelhos?", "alunos que usam laptops", "alunos que usam tablets", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Em um bairro, $a casas têm jardim, dessas casas, $aMb não têm garagem. Quantas casas possuem ambos?", "casas que têm jardim", "casas que têm garagem", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Em um curso, $a alunos gostam de biologia, e $aMb desses não gostam de química. Quantos gostam das duas matérias?", "alunos que gostam de biologia", "alunos que gostam de química", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("No parque, $a pessoas correram, e $aMb dessas não andaram de bicicleta. Quantas fizeram ambas as atividades?", "pessoas que correram", "pessoas que andaram de bicicleta", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Na empresa, $a funcionários participaram de treinamentos, e desses funcionários, $aMb não participaram de palestras. Quantos participaram dos dois?", "funcionários que participaram de treinamentos", "funcionários que participaram de palestras", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Em uma escola, $a alunos assistiram a aulas de teatro, desses alunos,  $aMb não assistiram a aulas de dança. Quantos fizeram as duas atividades?", "alunos que assistiram a aulas de teatro", "alunos que assistiram a aulas de dança", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("No clube, $a sócios jogam futebol, e desses sócios, $aMb não jogam vôlei. Quantos jogam os dois esportes?", "sócios que jogam futebol", "sócios que jogam vôlei", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Na livraria, dos $a clientes que compraram livros de ficção, $aMb que não compraram livros de poesia. Quantos compraram os dois tipos?", "clientes que compraram livros de ficção", "clientes que compraram livros de poesia", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Na escola, $a estudantes participam da banda, desses estudantes, $aMb que não participam do coral. Quantos participam dos dois grupos?", "estudantes que participam da banda", "estudantes que participam do coral", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Na cidade, $a moradores têm carro, e  $aMb desses moradores não têm moto. Quantos têm ambos os veículos?", "moradores que têm carro", "moradores que têm moto", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Em um grupo, $a pessoas têm conta no Instagram, sendo que $aMb delas não têm no TikTok. Quantas têm conta nas duas redes?", "pessoas com conta no Instagram", "pessoas com conta no TikTok", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("No condomínio, $a moradores participam da horta comunitária, desses moradores, $aMb não participam da reciclagem. Quantos participam de ambas?", "moradores que participam da horta comunitária", "moradores que participam da reciclagem", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Na universidade, $a alunos fazem parte do grêmio, desses alunos, $aMb não participam do centro acadêmico. Quantos fazem parte dos dois?", "alunos que fazem parte do grêmio", "alunos que participam do centro acadêmico", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Em uma ONG, $a voluntários atuam com crianças, desses voluntários, $aMb não atuam com idosos. Quantos atuam nos dois grupos?", "voluntários que atuam com crianças", "voluntários que atuam com idosos", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Na escola, $a alunos fazem reforço de matemática, desses alunos, $aMb não fazem reforço de português. Quantos fazem ambos?", "alunos que fazem reforço de matemática", "alunos que fazem reforço de português", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Na biblioteca, $a visitantes pegaram livros, sendo que $aMb desses visitantes não pegaram revistas. Quantos pegaram os dois?", "visitantes que pegaram livros", "visitantes que pegaram revistas", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Na escola, $a estudantes se inscreveram em espanhol, sendo que $aMb desses estudantes não se inscreveram em francês. Quantos se inscreveram nos dois?", "estudantes inscritos em espanhol", "estudantes inscritos em francês", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Na empresa, $a funcionários fizeram o curso de liderança, sendo que $aMb desses funcionários não fizeram o de gestão. Quantos fizeram ambos os cursos?", "funcionários que fizeram curso de liderança", "funcionários que fizeram curso de gestão", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("No festival, $a pessoas compraram ingresso para o sábado, sendo que $aMb dessas pessoas não compraram ingresso para o domingo. Quantas compraram para os dois dias?", "pessoas com ingresso para o sábado", "pessoas com ingresso para o domingo", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Na escola, $a alunos fizeram a prova de matemática, sendo que $aMb desses alunos não fizeram a de ciências. Quantos fizeram ambas as provas?", "alunos que fizeram a prova de matemática", "alunos que fizeram a prova de ciências", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Na quadra, $a jovens jogam futebol, sendo que $aMb desses jovens não jogam basquete. Quantos praticam os dois esportes?", "jovens que jogam futebol", "jovens que jogam basquete", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Na turma, $a alunos gostam de matemática, sendo que $aMb desses alunos não gostam de física. Quantos gostam das duas disciplinas?", "alunos que gostam de matemática", "alunos que gostam de física", TipoOperacaoMenos.AintersecB),
		new OperacoesMenos("Na loja, $a clientes compraram sapatos, sendo que $aMb desses clientes não compraram bolsas. Quantos compraram ambos os itens?", "clientes que compraram sapatos", "clientes que compraram bolsas", TipoOperacaoMenos.AintersecB),

	
		new OperacoesMenos("Em uma escola, $i alunos gostam de matemática e física, $aMb gostam só de matemática. Quantos gostam de matemática?", "alunos que gostam de matemática", "alunos que gostam de física", TipoOperacaoMenos.A),
		new OperacoesMenos("Num clube, $i membros participam de futebol e basquete, $aMb participam só de futebol. Quantos participam de futebol?", "membros que participam de futebol", "membros que participam de basquete", TipoOperacaoMenos.A),
		new OperacoesMenos("Em um parque, $i visitantes andam de bicicleta e patins, $aMb andam só de bicicleta. Quantos andam de bicicleta?", "visitantes que andam de bicicleta", "visitantes que andam de patins", TipoOperacaoMenos.A),
		new OperacoesMenos("No colégio, $i alunos estudam inglês e espanhol, $aMb estudam só inglês. Quantos estudam inglês?", "alunos que estudam inglês", "alunos que estudam espanhol", TipoOperacaoMenos.A),
		new OperacoesMenos("Em uma empresa, $i funcionários usam laptop e tablet, $aMb usam só laptop. Quantos usam laptop?", "funcionários que usam laptop", "funcionários que usam tablet", TipoOperacaoMenos.A),
		new OperacoesMenos("Num time, $i jogadores usam chuteiras e caneleiras, $aMb usam só chuteiras. Quantos usam chuteiras?", "jogadores que usam chuteiras", "jogadores que usam caneleiras", TipoOperacaoMenos.A),
		new OperacoesMenos("Em um evento, $i pessoas gostam de rock e pop, $aMb gostam só de rock. Quantas pessoas gostam de rock?", "pessoas que gostam de rock", "pessoas que gostam de pop", TipoOperacaoMenos.A),
		new OperacoesMenos("Na biblioteca, $i leitores pegam romance e mistério, $aMb pegam só romance. Quantos pegam romance?", "leitores que pegam romance", "leitores que pegam mistério", TipoOperacaoMenos.A),
		new OperacoesMenos("Em uma escola, $i alunos participam de teatro e dança, $aMb participam só de teatro. Quantos participam de teatro?", "alunos que participam de teatro", "alunos que participam de dança", TipoOperacaoMenos.A),
		new OperacoesMenos("No bairro, $i famílias têm cachorro e gato, $aMb têm só cachorro. Quantas famílias têm cachorro?", "famílias que têm cachorro", "famílias que têm gato", TipoOperacaoMenos.A),
		new OperacoesMenos("Num curso, $i alunos gostam de história e geografia, $aMb gostam só de história. Quantos gostam de história?", "alunos que gostam de história", "alunos que gostam de geografia", TipoOperacaoMenos.A),
		new OperacoesMenos("Em uma festa, $i convidados preferem refrigerante e suco, $aMb preferem só refrigerante. Quantos preferem refrigerante?", "convidados que preferem refrigerante", "convidados que preferem suco", TipoOperacaoMenos.A),
		new OperacoesMenos("No condomínio, $i moradores têm jardim e horta, $aMb têm só jardim. Quantos têm jardim?", "moradores que têm jardim", "moradores que têm horta", TipoOperacaoMenos.A),
		new OperacoesMenos("Na academia, $i alunos praticam corrida e ciclismo, $aMb praticam só corrida. Quantos praticam corrida?", "alunos que praticam corrida", "alunos que praticam ciclismo", TipoOperacaoMenos.A),
		new OperacoesMenos("Em uma escola, $i alunos gostam de biologia e química, $aMb gostam só de biologia. Quantos gostam de biologia?", "alunos que gostam de biologia", "alunos que gostam de química", TipoOperacaoMenos.A),
		new OperacoesMenos("Num clube, $i membros jogam tênis e squash, $aMb jogam só tênis. Quantos jogam tênis?", "membros que jogam tênis", "membros que jogam squash", TipoOperacaoMenos.A),
		new OperacoesMenos("Na empresa, $i funcionários têm carro e moto, $aMb têm só carro. Quantos têm carro?", "funcionários que têm carro", "funcionários que têm moto", TipoOperacaoMenos.A),
		new OperacoesMenos("Em uma cidade, $i pessoas utilizam ônibus e metrô, $aMb utilizam só ônibus. Quantas usam ônibus?", "pessoas que utilizam ônibus", "pessoas que utilizam metrô", TipoOperacaoMenos.A),
		new OperacoesMenos("No colégio, $i alunos participam do time de futebol e vôlei, $aMb participam só de futebol. Quantos participam do futebol?", "alunos que participam do time de futebol", "alunos que participam do time de vôlei", TipoOperacaoMenos.A),
		new OperacoesMenos("Em uma escola, $i alunos gostam de matemática e física, $aMb gostam só de matemática. Quantos gostam de matemática?", "alunos que gostam de matemática", "alunos que gostam de física", TipoOperacaoMenos.A),
		new OperacoesMenos("No ginásio, $i alunos praticam vôlei e basquete, $aMb praticam só vôlei. Quantos praticam vôlei?", "alunos que praticam vôlei", "alunos que praticam basquete", TipoOperacaoMenos.A),
		new OperacoesMenos("Em uma festa, $i pessoas gostam de jazz e blues, $aMb gostam só de jazz. Quantas pessoas gostam de jazz?", "pessoas que gostam de jazz", "pessoas que gostam de blues", TipoOperacaoMenos.A),
		new OperacoesMenos("Na biblioteca, $i leitores pegam livros de ficção e não-ficção, $aMb pegam só ficção. Quantos pegam ficção?", "leitores que pegam livros de ficção", "leitores que pegam livros de não-ficção", TipoOperacaoMenos.A),
		new OperacoesMenos("Em um parque, $i visitantes praticam corrida e yoga, $aMb praticam só corrida. Quantos praticam corrida?", "visitantes que praticam corrida", "visitantes que praticam yoga", TipoOperacaoMenos.A),
		new OperacoesMenos("Na escola, $i alunos estudam francês e alemão, $aMb estudam só francês. Quantos estudam francês?", "alunos que estudam francês", "alunos que estudam alemão", TipoOperacaoMenos.A),
		new OperacoesMenos("No clube, $i membros participam de xadrez e dama, $aMb participam só de xadrez. Quantos participam de xadrez?", "membros que participam de xadrez", "membros que participam de dama", TipoOperacaoMenos.A),
		new OperacoesMenos("Em uma empresa, $i funcionários falam inglês e espanhol, $aMb falam só inglês. Quantos falam inglês?", "funcionários que falam inglês", "funcionários que falam espanhol", TipoOperacaoMenos.A),
		new OperacoesMenos("No bairro, $i famílias têm internet e TV a cabo, $aMb têm só internet. Quantas famílias têm internet?", "famílias que têm internet", "famílias que têm TV a cabo", TipoOperacaoMenos.A),
		new OperacoesMenos("Em uma escola, $i alunos participam do clube de leitura e teatro, $aMb participam só do clube de leitura. Quantos participam do clube de leitura?", "alunos que participam do clube de leitura", "alunos que participam do clube de teatro", TipoOperacaoMenos.A),
		new OperacoesMenos("Na academia, $i alunos praticam natação e musculação, $aMb praticam só natação. Quantos praticam natação?", "alunos que praticam natação", "alunos que praticam musculação", TipoOperacaoMenos.A),
		new OperacoesMenos("No time de basquete, $i jogadores usam tênis e joelheiras, $aMb usam só tênis. Quantos usam tênis?", "jogadores que usam tênis", "jogadores que usam joelheiras", TipoOperacaoMenos.A),
		new OperacoesMenos("Em um evento, $i convidados gostam de comida italiana e japonesa, $aMb gostam só de comida italiana. Quantos gostam de comida italiana?", "convidados que gostam de comida italiana", "convidados que gostam de comida japonesa", TipoOperacaoMenos.A),
		new OperacoesMenos("Na escola, $i alunos estudam física e química, $aMb estudam só física. Quantos estudam física?", "alunos que estudam física", "alunos que estudam química", TipoOperacaoMenos.A),
		new OperacoesMenos("Em um parque, $i visitantes andam de skate e patins, $aMb andam só de skate. Quantos andam de skate?", "visitantes que andam de skate", "visitantes que andam de patins", TipoOperacaoMenos.A),
		new OperacoesMenos("No condomínio, $i moradores têm piscina e churrasqueira, $aMb têm só piscina. Quantos têm piscina?", "moradores que têm piscina", "moradores que têm churrasqueira", TipoOperacaoMenos.A),
		new OperacoesMenos("Em uma escola, $i alunos gostam de arte e música, $aMb gostam só de arte. Quantos gostam de arte?", "alunos que gostam de arte", "alunos que gostam de música", TipoOperacaoMenos.A),
		new OperacoesMenos("No time de futebol, $i jogadores usam camisa e calção, $aMb usam só camisa. Quantos usam camisa?", "jogadores que usam camisa", "jogadores que usam calção", TipoOperacaoMenos.A),
		new OperacoesMenos("Em uma biblioteca, $i leitores pegam livros de história e geografia, $aMb pegam só história. Quantos pegam história?", "leitores que pegam livros de história", "leitores que pegam livros de geografia", TipoOperacaoMenos.A),
		new OperacoesMenos("Na empresa, $i funcionários usam notebook e celular, $aMb usam só notebook. Quantos usam notebook?", "funcionários que usam notebook", "funcionários que usam celular", TipoOperacaoMenos.A),
		new OperacoesMenos("Em um clube, $i membros jogam tênis e futebol, $aMb jogam só tênis. Quantos jogam tênis?", "membros que jogam tênis", "membros que jogam futebol", TipoOperacaoMenos.A),
		new OperacoesMenos("No colégio, $i alunos participam de matemática e física, $aMb participam só de matemática. Quantos participam de matemática?", "alunos que participam de matemática", "alunos que participam de física", TipoOperacaoMenos.A),
		new OperacoesMenos("Em uma festa, $i pessoas preferem chá e café, $aMb preferem só chá. Quantas pessoas preferem chá?", "pessoas que preferem chá", "pessoas que preferem café", TipoOperacaoMenos.A),
		new OperacoesMenos("No bairro, $i famílias têm garagem e jardim, $aMb têm só garagem. Quantas famílias têm garagem?", "famílias que têm garagem", "famílias que têm jardim", TipoOperacaoMenos.A),
		new OperacoesMenos("Em um parque, $i visitantes praticam yoga e pilates, $aMb praticam só yoga. Quantos praticam yoga?", "visitantes que praticam yoga", "visitantes que praticam pilates", TipoOperacaoMenos.A),
		new OperacoesMenos("Na biblioteca, $i leitores pegam livros de ciência e tecnologia, $aMb pegam só ciência. Quantos pegam ciência?", "leitores que pegam livros de ciência", "leitores que pegam livros de tecnologia", TipoOperacaoMenos.A),
		new OperacoesMenos("Em um time, $i jogadores treinam ataque e defesa, $aMb treinam só ataque. Quantos treinam ataque?", "jogadores que treinam ataque", "jogadores que treinam defesa", TipoOperacaoMenos.A),
		new OperacoesMenos("Na escola, $i alunos participam de clube de robótica e programação, $aMb participam só de robótica. Quantos participam de robótica?", "alunos que participam de robótica", "alunos que participam de programação", TipoOperacaoMenos.A),
		new OperacoesMenos("Em uma empresa, $i funcionários falam francês e inglês, $aMb falam só francês. Quantos falam francês?", "funcionários que falam francês", "funcionários que falam inglês", TipoOperacaoMenos.A),
		new OperacoesMenos("No clube, $i membros jogam basquete e vôlei, $aMb jogam só basquete. Quantos jogam basquete?", "membros que jogam basquete", "membros que jogam vôlei", TipoOperacaoMenos.A),
		new OperacoesMenos("Em um cinema, $i espectadores assistem com pipoca e refrigerante, $aMb só com pipoca. Quantos assistem com pipoca?", "espectadores que assistem com pipoca", "espectadores que assistem com refrigerante", TipoOperacaoMenos.A),
		new OperacoesMenos("No curso de idiomas, $i alunos estudam inglês e francês, $aMb só inglês. Quantos estudam inglês?", "alunos que estudam inglês", "alunos que estudam francês", TipoOperacaoMenos.A),
		new OperacoesMenos("Em uma feira, $i visitantes compram frutas e verduras, $aMb só frutas. Quantos compram frutas?", "visitantes que compram frutas", "visitantes que compram verduras", TipoOperacaoMenos.A),
		new OperacoesMenos("Na biblioteca, $i leitores pegam livros de ficção e suspense, $aMb só ficção. Quantos pegam ficção?", "leitores que pegam livros de ficção", "leitores que pegam livros de suspense", TipoOperacaoMenos.A),
		new OperacoesMenos("No clube de música, $i membros tocam guitarra e bateria, $aMb só guitarra. Quantos tocam guitarra?", "membros que tocam guitarra", "membros que tocam bateria", TipoOperacaoMenos.A),
		new OperacoesMenos("Em um parque, $i visitantes fazem corrida e caminhada, $aMb só corrida. Quantos fazem corrida?", "visitantes que fazem corrida", "visitantes que fazem caminhada", TipoOperacaoMenos.A),
		new OperacoesMenos("Na escola, $i alunos participam do clube de xadrez e matemática, $aMb só xadrez. Quantos participam de xadrez?", "alunos que participam do clube de xadrez", "alunos que participam do clube de matemática", TipoOperacaoMenos.A),
		new OperacoesMenos("No condomínio, $i moradores têm piscina e academia, $aMb só piscina. Quantos têm piscina?", "moradores que têm piscina", "moradores que têm academia", TipoOperacaoMenos.A),
		new OperacoesMenos("Em uma empresa, $i funcionários usam computador e celular, $aMb só computador. Quantos usam computador?", "funcionários que usam computador", "funcionários que usam celular", TipoOperacaoMenos.A),
		new OperacoesMenos("No time de futebol, $i jogadores usam camisa e meiões, $aMb só camisa. Quantos usam camisa?", "jogadores que usam camisa", "jogadores que usam meiões", TipoOperacaoMenos.A),
		new OperacoesMenos("Na escola, $i alunos gostam de biologia e química, $aMb só biologia. Quantos gostam de biologia?", "alunos que gostam de biologia", "alunos que gostam de química", TipoOperacaoMenos.A),
		new OperacoesMenos("Em uma festa, $i pessoas preferem bolo e sorvete, $aMb só bolo. Quantas pessoas preferem bolo?", "pessoas que preferem bolo", "pessoas que preferem sorvete", TipoOperacaoMenos.A),
		new OperacoesMenos("No bairro, $i famílias têm carro e moto, $aMb só carro. Quantas famílias têm carro?", "famílias que têm carro", "famílias que têm moto", TipoOperacaoMenos.A),
		new OperacoesMenos("Em um parque, $i visitantes andam de bicicleta e patins, $aMb só bicicleta. Quantos andam de bicicleta?", "visitantes que andam de bicicleta", "visitantes que andam de patins", TipoOperacaoMenos.A),
		new OperacoesMenos("Na biblioteca, $i leitores pegam livros de história e geografia, $aMb só história. Quantos pegam história?", "leitores que pegam livros de história", "leitores que pegam livros de geografia", TipoOperacaoMenos.A),
		new OperacoesMenos("Em um time, $i jogadores treinam ataque e defesa, $aMb só ataque. Quantos treinam ataque?", "jogadores que treinam ataque", "jogadores que treinam defesa", TipoOperacaoMenos.A),
		new OperacoesMenos("Na escola, $i alunos estudam francês e espanhol, $aMb só francês. Quantos estudam francês?", "alunos que estudam francês", "alunos que estudam espanhol", TipoOperacaoMenos.A),
		new OperacoesMenos("No clube, $i membros participam de basquete e vôlei, $aMb só basquete. Quantos participam de basquete?", "membros que participam de basquete", "membros que participam de vôlei", TipoOperacaoMenos.A),
		new OperacoesMenos("Em uma empresa, $i funcionários falam inglês e espanhol, $aMb só inglês. Quantos falam inglês?", "funcionários que falam inglês", "funcionários que falam espanhol", TipoOperacaoMenos.A),
		new OperacoesMenos("No condomínio, $i moradores têm jardim e churrasqueira, $aMb só jardim. Quantos têm jardim?", "moradores que têm jardim", "moradores que têm churrasqueira", TipoOperacaoMenos.A),

	};
	
	public static OperacoesMenos getProblema()
	{
		Random rand=new Random();
		int index=rand.nextInt(problemas.length);
		return problemas[index].clone();
	}
	
}
