package Matematica.Basico.MmcMdc.Nivel2Package;

import java.util.Random;

import Matematica.Basico.MmcMdc.ProblemaMmcMdc;
import Matematica.Basico.MmcMdc.TipoProblema;

public class TextoMDC
{
	static ProblemaMmcMdc problemas[] = {
	new ProblemaMmcMdc("Dois canos de água, um de $a cm e outro de $b cm de comprimento, devem ser cortados em pedaços iguais. Qual o maior tamanho possível das peças?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Uma fábrica embala chocolates em caixas com $a ou $b unidades. Qual o maior número de caixas com a mesma quantidade que pode ser montado?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Dois lotes de tijolos, um com $a unidades e outro com $b, precisam ser divididos igualmente entre construtoras. Qual o maior número possível de construtoras?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Dois tipos de fio, um de $a metros e outro de $b metros, precisam ser cortados em pedaços iguais sem sobrar. Qual o maior tamanho dos pedaços?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Uma loja recebeu $a e $b bolas de dois tipos diferentes. Qual o maior número de kits idênticos que pode formar?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Um marceneiro tem tábuas de $a cm e $b cm e deseja cortá-las em partes iguais. Qual o maior tamanho possível das partes?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Uma escola quer dividir $a e $b lápis igualmente entre alunos. Qual o maior número de alunos possível?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Dois lotes de feijão de $a kg e $b kg devem ser embalados em sacos iguais. Qual o maior peso possível de cada saco?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Uma confecção tem rolos de tecido de $a e $b metros. Qual o maior comprimento possível para cortar pedaços iguais?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Um mercado vende pacotes de arroz de $a e $b kg. Qual o maior peso possível para embalar quantidades iguais?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Dois tanques de água, um com $a e outro com $b litros, precisam ser divididos em recipientes iguais. Qual o maior volume de cada?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Dois caminhões transportam $a e $b caixas. Qual o maior número de cargas iguais que podem ser organizadas?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Uma gráfica tem pilhas de $a e $b folhas. Qual o maior número de pacotes iguais que pode fazer?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Dois blocos de queijo de $a e $b kg precisam ser cortados em pedaços iguais. Qual o maior peso possível de cada pedaço?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Um pintor tem latas de tinta de $a e $b litros e quer dividir em recipientes iguais. Qual o maior volume possível?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Um conjunto de garrafas de $a e $b litros precisa ser distribuído em partes iguais. Qual o maior volume possível?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Duas fábricas produzem lotes de $a e $b peças. Qual o maior número de lotes idênticos que podem ser organizados?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Dois engenheiros organizam cabos de $a e $b metros. Qual o maior tamanho possível para cortar os cabos igualmente?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Dois rolos de fita adesiva medem $a cm e $b cm. Qual o maior comprimento que pode ser cortado em pedaços iguais de ambos?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Dois navios transportam cargas de $a e $b toneladas, respectivamente. Qual a maior capacidade de contêiner que pode ser usada para dividir igualmente ambas as cargas sem sobras?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Duas fábricas embalam pacotes de $a e $b produtos cada. Qual o maior número de itens por caixa que pode ser usado para embalar ambos sem sobrar?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Uma pessoa tem duas cordas de $a cm e $b cm. Qual o maior comprimento possível para cortá-las em pedaços iguais?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Dois irmãos querem dividir $a e $b figurinhas em pacotes iguais. Qual o maior número de figurinhas por pacote sem sobrar?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Dois feirantes têm caixas de $a e $b frutas. Qual o maior número de frutas por saco que pode ser feito sem sobrar nenhuma?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Dois jardineiros têm canteiros de $a e $b metros e querem dividi-los em partes iguais. Qual o maior tamanho possível?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Dois armazéns possuem sacos de $a e $b kg de grãos. Qual o maior peso possível para dividir igualmente sem sobrar?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Dois amigos colecionam moedas, um com $a e outro com $b. Qual o maior número de moedas que podem separar por pacotes iguais?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Dois eletricistas têm cabos de $a e $b metros. Qual o maior tamanho de fio que podem cortar igualmente?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Dois panificadores têm massas de $a e $b gramas. Qual o maior peso possível para fazer porções iguais?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Dois engenheiros querem cortar vigas de $a e $b cm em pedaços iguais. Qual o maior tamanho possível?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Dois vendedores têm caixas de $a e $b lápis. Qual o maior número de lápis que podem separar por estojo sem sobra?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Dois irmãos possuem $a e $b doces, respectivamente, e querem montar saquinhos com a mesma quantidade de doces, sem que sobre nenhum. Qual é o maior número de doces que cada saquinho pode conter?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Dois pedaços de fio de cobre, com $a cm e $b cm, devem ser cortados em pedaços do mesmo comprimento. Qual o maior tamanho possível?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Um confeiteiro tem bolos de $a e $b cm de diâmetro e quer cortar fatias iguais. Qual o maior tamanho possível das fatias?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Dois sacos de arroz de $a kg e $b kg devem ser embalados em pacotes iguais. Qual o maior peso possível de cada pacote?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Dois grupos de alunos, um com $a e outro com $b estudantes, devem ser divididos em grupos iguais. Qual o maior número de alunos por grupo?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Dois navios transportam $a e $b contêineres e precisam organizá-los em pilhas do mesmo tamanho. Qual o maior número de contêineres por pilha?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Dois eventos esportivos têm $a e $b participantes e devem ser divididos em times do mesmo tamanho. Qual o maior número de atletas por time?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Dois pedaços de fita de cetim de $a cm e $b cm devem ser cortados em partes iguais. Qual o maior comprimento possível de cada parte?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Dois containers armazenam $a e $b kg de mercadorias e devem ser divididos em partes iguais. Qual o maior peso possível de cada parte?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Dois armazéns têm estoques de $a e $b produtos e precisam organizá-los em prateleiras iguais. Qual o maior número de produtos por prateleira?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Dois pacotes de folhas de papel têm $a e $b folhas e devem ser divididos em pilhas iguais. Qual o maior número de folhas por pilha?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Dois vagões de trem transportam $a e $b sacas de café e precisam organizá-las em grupos do mesmo tamanho. Qual o maior número de sacas por grupo?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Dois carpinteiros possuem tábuas de $a e $b cm e precisam cortá-las em pedaços iguais. Qual o maior tamanho possível dos pedaços?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Dois painéis solares de $a e $b m devem ser divididos em partes iguais. Qual o maior tamanho possível de cada parte?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Dois feirantes têm $a e $b maçãs e precisam empacotá-las igualmente. Qual o maior número possível de maçãs por pacote?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Dois distribuidores têm pacotes de $a e $b unidades de produtos e precisam reembalar em caixas iguais. Qual o maior número possível por caixa?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Dois supermercados têm estoques de $a e $b produtos e precisam organizar em prateleiras iguais. Qual o maior número possível por prateleira?",
	TipoProblema.MdcDuas),
	new ProblemaMmcMdc("Dois jardineiros possuem $a e $b flores e querem organizá-las em buquês iguais. Qual o maior número possível de flores por buquê?",
	TipoProblema.MdcDuas),
	};

	public static ProblemaMmcMdc getProblemaMMC()
	{
		Random rand = new Random();
		int index = rand.nextInt(problemas.length);
		return problemas[index].clone();
	}

}
