package matematica.avancado.combinatoria.nivel1package;

import java.util.Random;

public class TextoPrincipioMultiplicacao
{
	static ProblemaPrincipioMultiplicacao  problemas[]= {
	new ProblemaPrincipioMultiplicacao("Há $a modelos de camisetas e $b modelos de calças. Quantas combinações camiseta-calça são possíveis?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Um cardápio tem $a tipos de entradas e $b tipos de sobremesas. Quantas refeições entrada-sobremesa podem ser feitas?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Uma agência oferece $a pacotes turísticos e $b seguros de viagem. Quantas combinações pacote-seguro são possíveis?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Em uma feira, há $a estandes de eletrônicos e $b de alimentação. Quantas combinações eletrônico-alimentação podemos fazer?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Na floricultura, há $a tipos de flores e $b tipos de vasos. Quantas combinações flor-vaso podem ser montadas?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Em uma sorveteria, há $a sabores de sorvete e $b tipos de cobertura. Quantas combinações sorvete-cobertura existem?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Na loja, há $a modelos de bolsas e $b modelos de sapatos. Quantas combinações bolsa-sapato podem ser feitas?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Em um evento, há $a palestras e $b workshops. Quantas combinações palestra-workshop podem ser escolhidas?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Na livraria, há $a gêneros de livros e $b editoras. Quantas combinações gênero-editora podem ser formadas?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Na academia, há $a modalidades de treino e $b horários disponíveis. Quantas combinações treino-horário podemos montar?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Para montar um look, há $a opções de blusas e $b opções de saias. Quantas combinações blusa-saia existem?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Em um restaurante, há $a opções de pratos principais e $b opções de sobremesas. Quantas combinações prato-sobremesa existem?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Na gráfica, há $a tipos de papéis e $b tipos de encadernação. Quantas combinações papel-encadernação podemos fazer?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("No shopping, há $a lojas de roupas e $b lojas de calçados. Quantas combinações de uma loja de roupa e uma loja de calçado podemos visitar?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("No buffet, há $a tipos de salgados e $b tipos de doces. Quantas combinações salgado-doce podem ser feitas?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Em um estúdio de fotos, há $a cenários e $b fantasias. Quantas combinações cenário-fantasia podem ser montadas?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Na escola, há $a clubes de esportes e $b clubes de música. Quantas combinações esporte-música são possíveis?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Na cafeteria, há $a tipos de cafés e $b tipos de bolos. Quantas combinações café-bolo podem ser escolhidas?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Em uma loja de móveis, há $a tipos de sofás e $b tipos de mesas. Quantas combinações sofá-mesa podem ser feitas?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("No mercado, há $a tipos de frutas e $b tipos de verduras. Quantas combinações fruta-verdura podem ser montadas?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("No aeroporto, há $a destinos e $b companhias aéreas. Quantas combinações destino-companhia podem ser feitas?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("No show, há $a tipos de ingressos e $b horários de entrada. Quantas combinações ingresso-horário podem ser feitas?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Em uma loja de eletrônicos, há $a modelos de celulares e $b tipos de capinhas. Quantas combinações celular-capinha existem?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("No salão de beleza, há $a estilos de corte e $b estilos de coloração. Quantas combinações corte-coloração existem?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Em uma pizzaria, há $a sabores de pizza e $b tipos de borda. Quantas combinações sabor-borda podem ser feitas?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Em um parque, há $a trilhas e $b passeios de barco. Quantas combinações trilha-passeio podem ser feitas?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Para personalizar um tênis, há $a opções de cores e $b estilos de cadarço. Quantas combinações cor-cadarço existem?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Em um curso, há $a métodos de ensino e $b temas disponíveis. Quantas combinações método-tema podemos formar?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Na loja de decoração, há $a estilos de luminárias e $b estilos de tapetes. Quantas combinações luminária-tapete existem?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Na oficina de arte, há $a cursos de pintura e $b cursos de escultura. Quantas combinações pintura-escultura podemos montar?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Em uma biblioteca, há $a categorias de livros e $b tipos de revistas. Quantas combinações livro-revista podem ser feitas?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("No workshop de fotografia, há $a temas e $b locações. Quantas combinações tema-locação podem ser feitas?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Na loja de esportes, há $a tipos de chuteiras e $b tipos de bolas. Quantas combinações chuteira-bola existem?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Em uma loja online, há $a modelos de tênis e $b cores de tênis. Quantas combinações modelo-cor podemos montar?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Em uma gráfica, há $a tipos de capa e $b tipos de papel. Quantas combinações capa-papel podem ser feitas?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Em uma escola de idiomas, há $a idiomas e $b tipos de cursos. Quantas combinações idioma-curso podem ser feitas?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Em uma loja de instrumentos, há $a tipos de guitarras e $b tipos de amplificadores. Quantas combinações guitarra-amplificador podem ser feitas?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Na papelaria, há $a tipos de cadernos e $b tipos de canetas. Quantas combinações caderno-caneta podem ser feitas?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Em uma loja de pets, há $a rações para cães e $b rações para gatos. Quantas combinações uma ração de cão e uma ração de gato podem ser feitas?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("No buffet infantil, há $a tipos de brinquedos e $b tipos de comidas. Quantas combinações brinquedo-comida podem ser feitas?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Em uma loja de roupas, há $a estilos de jaquetas e $b estilos de calças. Quantas combinações jaqueta-calça existem?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Na padaria, há $a tipos de pães e $b tipos de recheios. Quantas combinações pão-recheio podem ser feitas?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("No evento de dança, há $a estilos de dança e $b coreografias. Quantas combinações estilo-coreografia podem ser feitas?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Na loja de cosméticos, há $a bases de maquiagem e $b batons. Quantas combinações base-batom podem ser escolhidas?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("No parque aquático, há $a tipos de toboáguas e $b tipos de piscinas. Quantas combinações toboágua-piscina podemos fazer?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Em uma loja de bicicletas, há $a modelos de bicicletas e $b capacetes. Quantas combinações bicicleta-capacete existem?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Na loja de brinquedos, há $a tipos de jogos e $b tipos de bonecos. Quantas combinações jogo-boneco podem ser feitas?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("No festival de cinema, há $a filmes e $b sessões especiais. Quantas combinações filme-sessão podem ser escolhidas?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Na loja de informática, há $a modelos de notebooks e $b tipos de impressoras. Quantas combinações notebook-impressora podem ser feitas?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("No acampamento, há $a trilhas e $b atividades noturnas. Quantas combinações trilha-atividade noturna podem ser feitas?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Na exposição de carros, há $a marcas de carros e $b tipos de pneus. Quantas combinações escolhendo uma marca de carro e um tipo de pneu podemos formar?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Em uma loja de jardinagem, há $a tipos de sementes e $b tipos de adubos. Quantas combinações semente-adubo podem ser feitas?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Em um estúdio de gravação, há $a microfones e $b tipos de fones. Quantas combinações microfone-fone podem ser feitas?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("No campeonato esportivo, há $a modalidades e $b categorias de idade. Quantas combinações modalidade-categoria podemos formar?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("No parque de diversões, há $a montanhas-russas e $b rodas-gigantes. Quantas combinações montanha-roda podem ser feitas?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("No estande de perfumes, há $a fragrâncias e $b tipos de embalagens. Quantas combinações fragrância-embalagem existem?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Em uma escola de teatro, há $a peças de comédia e $b peças de drama. Quantas combinações comédia-drama podem ser feitas?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("No concurso de culinária, há $a receitas doces e $b receitas salgadas. Quantas combinações doce-salgado podemos fazer?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("No curso de moda, há $a tipos de tecidos e $b tipos de estampas. Quantas combinações tecido-estampa podem ser feitas?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Na aula de fotografia, há $a tipos de lentes e $b tipos de câmeras. Quantas combinações lente-câmera podem ser feitas?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Em um bazar, há $a tipos de brinquedos e $b tipos de roupas. Quantas combinações brinquedo-roupa podem ser escolhidas?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Em uma escola de música, há $a tipos de instrumentos e $b tipos de partituras. Quantas combinações instrumento-partitura existem?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("No festival literário, há $a livros nacionais e $b livros estrangeiros. Quantas combinações nacional-estrangeiro podem ser feitas?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("No evento geek, há $a painéis de séries e $b painéis de games. Quantas combinações série e game existem?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Na feira de profissões, há $a cursos de exatas e $b cursos de humanas. Quantas combinações exatas-humanas podem ser feitas?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("No buffet de casamento, há $a entradas e $b pratos principais. Quantas combinações entrada-prato existem?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Na loja de acessórios, há $a tipos de colares e $b tipos de brincos. Quantas combinações colar-brinco podem ser feitas?", TipoPrincipioMultiplicacao.Duas),
	new ProblemaPrincipioMultiplicacao("Na cafeteria, há $a tipos de chás e $b tipos de bolos. Quantas combinações chá-bolo podem ser feitas?", TipoPrincipioMultiplicacao.Duas),
//
	new ProblemaPrincipioMultiplicacao("Em uma loja, há $a tipos de camisas, $b tipos de calças e $c tipos de sapatos. Quantas combinações camisa-calça-sapato podem ser feitas?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("No restaurante, há $a entradas, $b pratos principais e $c sobremesas. Quantas combinações entrada-prato-sobremesa podemos montar?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("Em uma cafeteria, há $a tipos de cafés, $b tipos de bolos e $c tipos de tortas. Quantas combinações café-bolo-torta podem ser feitas?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("Na papelaria, há $a tipos de cadernos, $b tipos de canetas e $c tipos de mochilas. Quantas combinações caderno-caneta-mochila podem ser feitas?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("Na gráfica, há $a tipos de capas, $b tipos de papéis e $c tipos de encadernações. Quantas combinações capa-papel-encadernação existem?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("No buffet, há $a tipos de salgados, $b tipos de doces e $c tipos de bebidas. Quantas combinações salgado-doce-bebida podem ser feitas?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("Na loja de informática, há $a tipos de notebooks, $b tipos de impressoras e $c tipos de acessórios. Quantas combinações notebook-impressora-acessório existem?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("Na floricultura, há $a tipos de flores, $b tipos de vasos e $c tipos de enfeites. Quantas combinações flor-vaso-enfeite podem ser montadas?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("Na sorveteria, há $a sabores de sorvete, $b tipos de coberturas e $c tipos de casquinhas. Quantas combinações sorvete-cobertura-casquinha existem?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("No estúdio de fotos, há $a cenários, $b fantasias e $c tipos de maquiagens. Quantas combinações cenário-fantasia-maquiagem podem ser feitas?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("No aeroporto, há $a destinos, $b companhias aéreas e $c horários de voo. Quantas combinações destino-companhia-horário podemos fazer?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("No shopping, há $a lojas de roupas, $b lojas de calçados e $c lojas de acessórios. Quantas combinações roupa-calçado-acessório podemos montar?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("No festival, há $a filmes, $b sessões especiais e $c workshops. Quantas combinações filme-sessão-workshop podem ser feitas?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("Na academia, há $a modalidades de treino, $b horários disponíveis e $c tipos de instrutores. Quantas combinações treino-horário-instrutor existem?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("Na loja de acessórios, há $a tipos de colares, $b tipos de brincos e $c tipos de pulseiras. Quantas combinações colar-brinco-pulseira podemos montar?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("Na cafeteria, há $a tipos de chás, $b tipos de bolos e $c tipos de tortas. Quantas combinações chá-bolo-torta podem ser feitas?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("No parque aquático, há $a tipos de toboáguas, $b tipos de piscinas e $c tipos de brinquedos aquáticos. Quantas combinações toboágua-piscina-brinquedo existem?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("Na loja de roupas, há $a estilos de jaquetas, $b estilos de calças e $c estilos de camisas. Quantas combinações jaqueta-calça-camisa podem ser feitas?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("Em um evento geek, há $a painéis de séries, $b painéis de games e $c painéis de animes. Quantas combinações série-game-anime podemos fazer?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("No aniversário, há $a sabores de bolo, $b sabores de doces e $c tipos de salgados. Quantas combinações bolo-doce-salgado podem ser feitas?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("Em uma exposição, há $a tipos de quadros, $b tipos de esculturas e $c tipos de fotografias. Quantas combinações quadro-escultura-foto podemos montar?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("Em uma loja de móveis, há $a tipos de sofás, $b tipos de mesas e $c tipos de cadeiras. Quantas combinações sofá-mesa-cadeira podem ser feitas?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("No show, há $a setores de entrada, $b horários de abertura e $c bandas. Quantas combinações setor-horário-banda podem ser escolhidas?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("Na festa à fantasia, há $a tipos de fantasias, $b tipos de máscaras e $c tipos de acessórios. Quantas combinações fantasia-máscara-acessório existem?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("Em um cardápio, há $a tipos de pizzas, $b tipos de bebidas e $c tipos de sobremesas. Quantas combinações pizza-bebida-sobremesa podem ser feitas?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("No mercado, há $a marcas de arroz, $b marcas de feijão e $c marcas de macarrão. Quantas combinações arroz-feijão-macarrão podemos comprar?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("No parque, há $a tipos de brinquedos, $b tipos de lanches e $c tipos de atividades. Quantas combinações brinquedo-lanche-atividade podem ser feitas?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("Na livraria, há $a categorias de livros, $b revistas e $c jornais. Quantas combinações livro-revista-jornal podemos escolher?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("Na oficina, há $a tipos de pneus, $b tipos de óleos e $c tipos de baterias. Quantas combinações pneu-óleo-bateria podem ser feitas?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("No hotel, há $a tipos de quartos, $b tipos de refeições e $c tipos de passeios. Quantas combinações quarto-refeição-passeio existem?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("Na escola, há $a clubes de esporte, $b clubes de ciência e $c clubes de arte. Quantas combinações esporte-ciência-arte podemos montar?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("Em um laboratório, há $a tipos de experimentos, $b tipos de reagentes e $c tipos de instrumentos. Quantas combinações experimento-reagente-instrumento podem ser feitas?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("Na agência de viagens, há $a destinos, $b pacotes turísticos e $c opções de hospedagem. Quantas combinações destino-pacote-hospedagem existem?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("Na feira de tecnologia, há $a modelos de celulares, $b modelos de notebooks e $c modelos de tablets. Quantas combinações celular-notebook-tablet podemos formar?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("Na pizzaria, há $a massas, $b molhos e $c recheios disponíveis. Quantas combinações massa-molho-recheio podemos criar?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("No campo, há $a tipos de plantações, $b tipos de fertilizantes e $c tipos de defensivos agrícolas. Quantas combinações plantação-fertilizante-defensivo podem ser feitas?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("Na estação de esqui, há $a tipos de pistas, $b tipos de equipamentos e $c tipos de instrutores. Quantas combinações pista-equipamento-instrutor existem?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("Na doceria, há $a tipos de cupcakes, $b tipos de balas e $c tipos de chocolates. Quantas combinações cupcake-bala-chocolate podem ser feitas?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("Na loja de brinquedos, há $a tipos de bonecos, $b tipos de jogos e $c tipos de carrinhos. Quantas combinações boneco-jogo-carrinho existem?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("No zoológico, há $a tipos de mamíferos, $b tipos de aves e $c tipos de répteis. Quantas combinações mamífero-ave-réptil podemos ver?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("No spa, há $a tipos de massagens, $b tipos de banhos e $c tipos de terapias. Quantas combinações massagem-banho-terapia podem ser feitas?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("Em uma escola de música, há $a tipos de instrumentos, $b gêneros musicais e $c tipos de apresentações. Quantas combinações instrumento-gênero-apresentação existem?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("No festival de comida, há $a estandes de hambúrgueres, $b estandes de pizzas e $c estandes de doces. Quantas combinações hambúrguer-pizza-doce podem ser feitas?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("Na loja de decoração, há $a tipos de quadros, $b tipos de cortinas e $c tipos de tapetes. Quantas combinações quadro-cortina-tapete podem ser feitas?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("No evento de ciências, há $a experiências químicas, $b experiências físicas e $c experiências biológicas. Quantas combinações química-física-biologia podem ser feitas?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("No campeonato de dança, há $a estilos de dança, $b categorias etárias e $c níveis de habilidade. Quantas combinações estilo-categoria-nível podem ser feitas?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("No festival de música, há $a shows de rock, $b shows de pop e $c shows de samba. Quantas combinações rock-pop-samba podem ser vistas?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("Na loja de instrumentos, há $a tipos de violões, $b tipos de baterias e $c tipos de teclados. Quantas combinações violão-bateria-teclado podem ser feitas?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("No centro cultural, há $a oficinas de pintura, $b oficinas de dança e $c oficinas de teatro. Quantas combinações pintura-dança-teatro existem?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("No restaurante vegetariano, há $a pratos principais, $b acompanhamentos e $c sobremesas veganas. Quantas combinações prato-acompanhamento-sobremesa podem ser feitas?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("No centro esportivo, há $a quadras de tênis, $b quadras de futebol e $c quadras de basquete. Quantas combinações tênis-futebol-basquete podem ser feitas?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("No teatro, há $a peças infantis, $b peças adultas e $c peças musicais. Quantas combinações infantil-adulto-musical podem ser vistas?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("Em uma cafeteria, há $a tipos de cafés, $b tipos de leites e $c tipos de xaropes. Quantas combinações café-leite-xarope podem ser criadas?", TipoPrincipioMultiplicacao.Tres),
	new ProblemaPrincipioMultiplicacao("No concurso cultural, há $a temas literários, $b temas musicais e $c temas de cinema. Quantas combinações literatura-música-cinema podem ser feitas?", TipoPrincipioMultiplicacao.Tres),

	};
	
	public static ProblemaPrincipioMultiplicacao getProblema()
	{
		Random rand=new Random();
		int index=rand.nextInt(problemas.length);
		return problemas[index].clone();
	}
	
}
