package matematica.avancado.combinatoria.nivel3package;

import java.text.Normalizer;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.regex.Pattern;

import matematica.avancado.combinatoria.AuxCombinacao;

public class TextoAnagramas
{
	static String  palavras[]= {
		"abaixai","abaixei","abarcar","abdicai","abeirai","abeirar","abeirei","abismai","abismam","abismas",
		"abjurar","abobada","abobada","abobada","abobade","abobado","aboboda","abobora","abonado","abordar",
		"abortar","abotoa","abotoai","abotoam","abotoar","abotoas","abracar","abrasar","abrasas","abrases",
		"abrigai","abrigar","abrira","abriram","abriras","abrirei","abriria","abusais","abusas","acacia",
		"acacias","acalmam","acalmem","acaloro","acampam","acampem","acasos","aceitai","aceitei","acelera",
		"acerca","acercai","acercam","acercar","acercas","acertar","acesas","acessa","acessai","acessam",
		"acessar","acessas","acesse","acessei","acessem","acesses","acetato","achasse","acicate","acionai",
		"acirra","acirrai","acirram","acirrar","acirras","acirrei","aclamam","aclamem","aclarar","acoitai",
		"acomoda","acordar","acorra","acorram","acorras","acorria","acorro","acossa","acossai","acossam",
		"acossar","acossas","acosso","acossou","acresce","acuasse","acumula","acusais","acusas","adensas",
		"adenses","aderira","adernar","adesoes","adiado","adiai","adiais","adiando","adiarei","adiaria",
		"adiasse","adida","adidas","adirais","adiria","adiriam","adirias","aditado","aditai","aditais",
		"aditiva","admirai","admiram","admirar","admitam","admitia","adocado","adocamo","adocica","adocico",
		"adorada","adorado","adoramo","adorar","adorara","adorara","adornar","adotada","adotado","adotamo",
		"adubada","adubado","adulado","adviria","afanoso","afastas","afastes","aferira","aferra","aferrai",
		"aferram","aferrar","aferras","aferre","aferrei","aferrem","aferres","aferroa","aferroe","afiai",
		"afiais","afiarei","afiaria","afiasse","afilia","afiliai","afiliam","afiliar","afilias","afinai",
		"afinais","afincai","afirais","afirmai","afirmam","afirmar","afixai","afixais","afligia","aflorar",
		"afobado","afobamo","afofa","afofado","afofai","afofais","afofam","afofamo","afofar","afofara",
		"afofara","afofas","afofava","afofemo","afofo","afofou","afogado","afogamo","afoitai","aforado",
		"aforamo","aforar","aforara","aforara","agarra","agarra","agarrai","agarram","agarrar","agarras",
		"agarre","agarrei","agarrem","agarres","agarro","agarrou","agiliza","agiotai","agiria","agiriam",
		"agirias","agitai","agitais","agourar","agourou","agradar","agraria","agravar","agrega","agregai",
		"agregam","agregar","agregas","agregue","agrupar","agruras","aguasse","airosas","airosos","ajeitai",
		"ajeitei","ajudada","ajudado","ajuizai","ajustas","alanina","alargar","alarmam","alarmar","alarmem",
		"alcance","alcasse","alcool","alegrar","aleijai","aleijei","aleitai","aleitei","aleluia","alertar",
		"alfafa","algemam","algemem","aliai","aliais","aliarei","aliaria","aliasse","alicia","aliciai",
		"aliciam","aliciar","alicias","alienai","alienei","alijai","alijais","alinhai","alisai","alisais",
		"alisas","aliseis","alistai","alistas","alivia","aliviai","aliviam","aliviar","alivias","almejam",
		"almejem","almocam","alocado","alocamo","alojado","alojamo","alourar","alourou","alterar","aluguel",
		"alumiai","alumiam","alveolo","amaciai","amaciam","amaciei","amaciem","amainai","amainam","amainei",
		"amainem","amam","amamo","amamos","amansam","amansas","amansem","amanses","amaram","amarele",
		"amarem","amaremo","amargam","amargar","amargor","amariam","amarmo","amarmos","amarra","amarra",
		"amarrai","amarram","amarrar","amarras","amarre","amarrei","amarrem","amarres","amarro","amarrou",
		"amasiai","amasiam","amasias","amasiei","amasiem","amasies","amassa","amassa","amassai","amassam",
		"amassar","amassas","amasse","amassei","amassem","amasses","amasso","amassou","amastes","amavam",
		"ameacam","ameace","ameacei","ameacem","ameaces","amigai","amigais","amigam","amigamo","amima",
		"amimado","amimai","amimais","amimam","amimamo","amimar","amimara","amimara","amimas","amimava",
		"amimei","amimeis","amiudai","amiudam","amoitai","amoitam","amolado","amolam","amolamo","amoldam",
		"amolemo","amontoa","amorosa","amparam","amparar","amparem","ampliai","ampliam","amputam","ananas",
		"ancorar","andado","andanca","andando","andante","andasse","andrade","angina","anilina","animai",
		"animais","animam","animamo","aninha","aninhai","aninham","aninhar","aninhas","aninhei","anistia",
		"anonima","anotado","anotamo","anseias","anseies","ansiai","ansiais","ansieis","ansiosa","ansioso",
		"antena","antenas","antonio","anuiria","anuncia","apalpa","apalpa","apalpai","apalpam","apalpar",
		"apalpas","apalpe","apalpei","apalpem","apalpes","apalpo","apalpou","aparar","aparara","aparara",
		"aparece","apartar","apavoro","apearei","apearem","apeares","apeasse","apeaste","aperrea","apertar",
		"apeteca","apetite","apiedai","apiedei","apinhai","apitai","apitais","aplicai","apoiado","apoiai",
		"apoiais","apoiamo","aportar","apossa","apossai","apossam","apossar","apossas","aposso","apossou",
		"apostas","apostos","aprazer","apresar","apresas","apreses","apressa","apresse","aprovar","aprumam",
		"aprumar","apurar","apurara","apurara","aqueceu","aquosas","aquosos","arar","arara","arara",
		"araram","ararao","araras","araras","Ararat","arardes","ararei","arareis","ararem","araremo",
		"arares","araria","arariam","ararias","ararmo","ararmos","araruta","arasse","arassem","arasses",
		"arastes","arbitra","arborea","arcaica","arcaico","arcar","arcara","arcara","arcaram","arcarao",
		"arcaras","arcaras","arcarei","arcarem","arcares","arcaria","arcarmo","arcasse","ardera","arderam",
		"arderas","arderei","arderem","arderes","arderia","ardesse","ardida","ardidas","arejar","arejara",
		"arejara","arestas","arfar","arfara","arfara","arfaram","arfarao","arfaras","arfaras","arfarei",
		"arfarem","arfares","arfaria","arfarmo","arfasse","arguira","ariscas","armador","armam","armamo",
		"armamos","armar","armara","armara","armaram","armarao","armaras","armaras","armarei","armarem",
		"armares","armaria","armarmo","armasse","armavam","armazem","aroeira","arpoado","arpoamo","arpoar",
		"arpoara","arpoara","arquear","arraia","arraial","arraias","arraiga","arraiga","arraigo","arranca",
		"arranca","arranco","arranha","arranha","arranhe","arranho","arranja","arranja","arranje","arranjo",
		"arrasa","arrasa","arrasai","arrasam","arrasar","arrasas","arrase","arrasei","arrasem","arrases",
		"arraso","arrasou","arrasta","arrasta","arraste","arrasto","arrazoa","arrazoa","arrazoe","arreada",
		"arreado","arreai","arreais","arreamo","arrear","arreara","arreara","arreava","arreda","arredai",
		"arredam","arredar","arredas","arrede","arredei","arredem","arredes","arredia","arreia","arreiam",
		"arreias","arreie","arreiem","arreies","arrenda","arrende","arrepia","arrepie","arria","arriado",
		"arriai","arriais","arriam","arriamo","arriar","arriara","arriara","arrias","arriava","arriba",
		"arribai","arribam","arribar","arribas","arribei","arriei","arrieis","arrima","arrimai","arrimam",
		"arrimar","arrimas","arrimei","arrimem","arrisca","arroba","arrobai","arrobam","arrobar","arrobas",
		"arrobo","arrobou","arrocha","arrocho","arroga","arrogai","arrogam","arrogar","arrogas","arrogo",
		"arrogou","arroio","arroios","arroja","arrojai","arrojam","arrojar","arrojas","arrojo","arrojou",
		"arrola","arrolai","arrolam","arrolar","arrolas","arrolha","arrolho","arrolo","arrolou","arromba",
		"arrombo","arrosta","arrosto","arrota","arrotai","arrotam","arrotar","arrotas","arroto","arrotos",
		"arrotou","arroubo","arruaca","arruda","arrudas","arruela","arruina","arruma","arrumai","arrumam",
		"arrumar","arrumas","arrumem","arrumou","arteira","arteria","artista","artrite","arvora","arvorai",
		"arvoram","arvorar","arvoras","arvoro","arvorou","asas","ascese","asceses","ascetas","asfixia",
		"asilai","asilais","asilas","asileis","aspas","aspirai","aspirar","aspiras","assa","assada",
		"assadas","assado","assados","assai","assais","assalta","assalta","assalte","assalto","assam",
		"assamo","assamos","assando","assanha","assanha","assanhe","assanho","assar","assara","assara",
		"assaram","assarao","assaras","assaras","assarei","assarem","assares","assaria","assarmo","assas",
		"assasse","assaste","assava","assavam","assavas","assaz","asseada","asseado","asseai","asseais",
		"asseamo","assear","asseara","asseara","asseava","assecla","assedia","assedie","asseia","asseiam",
		"asseias","asseie","asseiem","asseies","assenta","assente","assidua","assina","assinai","assinam",
		"assinar","assinas","assinei","assinta","assiria","assista","assisti","assoa","assoado","assoai",
		"assoais","assoam","assoamo","assoar","assoara","assoara","assoas","assoava","assobia","assobio",
		"associa","associo","assoemo","assola","assolai","assolam","assolar","assolas","assolo","assolou",
		"assoma","assomai","assomam","assomar","assomas","assomem","assomo","assomos","assomou","assopra",
		"assopro","assovia","assovio","assuma","assumam","assumas","assumem","assumia","assumiu","assusta",
		"astecas","astuta","astutas","astutos","atapeta","atapeta","atapete","atapeto","atasse","atassem",
		"atasses","ataste","atastes","ataviai","ataviei","atearei","atearem","ateares","ateasse","ateaste",
		"ateista","atenta","atentai","atentam","atentar","atentas","atente","atentei","atentem","atentes",
		"aterra","aterrai","aterram","aterrar","aterras","aterre","aterrei","aterrem","aterres","atesta",
		"atestai","atestam","atestar","atestas","ateste","atestei","atestem","atestes","aticai","aticais",
		"atinai","atinais","atingia","atirai","atirais","atirar","atirara","atirara","ativai","ativais",
		"ativava","atlante","atleta","atletas","atolado","atolamo","atonita","atordoa","atracar","atrair",
		"atraira","atraira","atrasar","atrasas","atrases","atrator","atrelar","atrever","atrita","atritai",
		"atritam","atritar","atritas","atritei","atuasse","atuaste","aturar","aturara","aturara","augura",
		"augurai","auguram","augurar","auguras","augusta","aurora","auroras","autista","autua","autuado",
		"autuai","autuais","autuam","autuamo","autuar","autuara","autuara","autuas","autuava","auxilia",
		"avaliai","avaliei","avariai","avariar","avariei","averbar","avessa","avessas","aviai","aviais",
		"aviarei","aviaria","aviasse","aviava","aviavam","aviavas","aviesse","aviltai","aviria","aviriam",
		"avirias","avisai","avisais","avisas","avisava","aviseis","avistai","avistas","aviva","avivada",
		"avivado","avivai","avivais","avivam","avivamo","avivar","avivara","avivara","avivas","avivava",
		"avivei","aviveis","avoado","avoados","avulsas","axiais","azarar","azarara","azarara","azedado",
		"azeitai","azeitei","azotado","baba","babado","babados","babai","babais","babam","babamo",
		"babamos","babando","babar","babara","babara","babaram","babarao","babaras","babaras","babarei",
		"babarem","babares","babaria","babarmo","babas","babasse","babaste","babava","babavam","babavas",
		"babosa","bagagem","bailai","bailais","baixai","baixais","balela","balelas","baliria","balizai",
		"balsas","bamba","bambas","bambeai","bambear","bambeia","bambeie","banana","bananal","bananas",
		"bandida","baniria","barba","barbaca","barbada","barbado","barbara","barbaro","barbas","barbeai",
		"barbear","barbeia","barbeie","barbosa","barra","barraca","barrado","barrai","barrais","barram",
		"barramo","barrar","barrara","barrara","barras","barrava","barrete","barrica","barriga","barroca",
		"barroco","Barroso","baseais","baseias","baseies","basista","bastais","bastas","batata","batatas",
		"batesse","bateste","batista","batizai","batota","batotas","batuta","batutas","bebe","bebei",
		"bebeis","bebem","bebemo","bebemos","bebendo","beber","bebera","bebera","beberam","beberao",
		"beberas","beberas","beberei","beberem","beberes","beberia","bebermo","bebes","bebesse","bebeste",
		"bebeu","bebieis","beijei","beijeis","beirara","beirei","beireis","benzeno","bereba","berebas",
		"berrara","berrava","berre","berrei","berreis","berrem","berremo","berres","betumem","bezerra",
		"bezerro","bicaria","biciclo","bigamia","biombo","biombos","biotipo","bizarra","bobeado","bobeamo",
		"bobeara","bobeava","bobeie","bobeiem","bobeies","bobeio","bobeou","bobo","bobos","boiaria",
		"boieiro","bolsos","bombeie","bombeio","bombeou","bombom","bombons","bonanca","bordada","bordado",
		"bordara","bororo","bororos","borrada","borrado","borramo","borrao","borrara","borrava","borremo",
		"borrifo","borro","borrou","braba","brabas","brabeza","bradado","bradar","bradara","bradara",
		"bramam","bramamo","bramar","bramara","bramara","bramiam","bramira","brasas","bravura","brecara",
		"brigara","briosos","brocara","brotara","burlara","busques","cabecea","cabocla","caboclo","cacasse",
		"cachaca","cacheai","cachear","cacheia","cacheie","cachola","cacoado","cacoamo","cadeado","caduca",
		"caducai","caducam","caducar","caducas","caducou","caiai","caiais","caiarei","caiaria","caiasse",
		"caibais","caipira","cairia","cairiam","cairias","calasse","calca","calcada","calcado","calcai",
		"calcais","calcam","calcamo","calcar","calcara","calcara","calcas","calcava","calcina","calcula",
		"calcula","calcule","calculo","calculo","camarim","cambiai","cambiam","camisas","canina","caninas",
		"caninha","canjica","cansais","cansas","cantata","cantina","capacho","capasse","capinai","caracol",
		"carbura","carcaca","carcere","careca","carecas","carece","carecei","carecem","carecer","careces",
		"careceu","carecia","careira","caricia","carioca","cariri","cariris","carpira","carrada","carrega",
		"carreta","caruru","carurus","casaca","casacao","casacas","casaco","casacos","casadas","casados",
		"casais","casamos","casaras","casaras","casares","casas","casasse","casaste","casavas","casca",
		"cascas","cascata","cascos","cassa","cassado","cassai","cassais","cassam","cassamo","cassar",
		"cassara","cassara","cassas","cassava","cassete","castas","castrar","castras","casuais","casulas",
		"catarro","catasse","cataste","catraca","causais","causas","cavaco","cavacos","cavasse","cavava",
		"cavavam","cavavas","caviai","caviais","caviava","cavoca","cavocai","cavocam","cavocar","cavocas",
		"cavoco","cavocou","cavouca","cavouco","ceasse","ceassem","ceasses","ceastes","cedendo","cedesse",
		"cegasse","ceifei","ceifeis","centena","cercada","cercar","cercara","cercara","cercava","cerrada",
		"cerrara","cerrava","cerre","cerrei","cerreis","cerrem","cerremo","cerres","cessara","cessava",
		"cesse","cessei","cesseis","cessem","cessemo","cesses","cetaceo","chacais","chacal","chacara",
		"cancha","caneca","canecas","checada","checara","checava","chefiei","cheirei","chiaria","chicara",
		"chocado","chocamo","chocara","chocava","chocha","chochas","chocho","chochos","choco","chocou",
		"chorara","chuchu","chuchus","ciatico","ciencia","cifrara","cigarra","ciliada","cilicio","cindida",
		"cindido","ciosos","ciscai","ciscais","ciscara","ciscas","ciscava","ciscos","cismais","cismeis",
		"citaria","clamam","clamamo","clarear","clinica","clinica","clinico","coajamo","coatora","coaxado",
		"coaxamo","cobicei","cobrara","cocada","cocadas","cocemo","cocemos","cochilo","cocho","cochos",
		"coco","cocos","coesos","coibido","coibimo","colchao","coloca","coloca","colocai","colocam",
		"colocar","colocas","coloco","colocou","colorir","colosso","comamo","comamos","comarca","comece",
		"comecei","comecem","comeces","comemo","comemos","comerem","comermo","comesse","cometem","comicio",
		"comovam","comovem","compomo","comutou","concava","concebe","concebo","concede","concedo","conciso",
		"concluo","condado","condene","condeno","conecte","conecto","confino","conhece","conosco","contata",
		"contato","convivi","convivo","convoca","convoca","convoco","corara","coraram","corarao","coraras",
		"coraria","corarmo","corcova","corisco","coroada","coroar","coroara","coroara","coroava","coroca",
		"corocas","corramo","correio","corremo","correto","corrido","corrigi","corrijo","corro","corroa",
		"corroam","corroas","corroe","corroe","corroei","corroem","corroer","corroes","corroeu","corroi",
		"corroia","cortara","cosamos","cosemos","coseres","cosesse","coseste","cosmos","cossaco","cosseno",
		"cozesse","cratera","cravar","cravara","cravara","cravava","creche","creches","cremara","cremem",
		"crememo","crerdes","crerei","crereis","crerem","creremo","creres","cresce","crescei","crescem",
		"crescer","cresces","cresceu","cresse","cressem","cresses","crestes","criara","criaram","criaras",
		"criarei","criaria","critica","critica","critico","crivara","crivava","cromamo","cromara","cromemo",
		"cruzara","cumbuca","cumulam","cumulem","curara","curaram","curaras","curaria","cursara","curvara",
		"curvava","cuscuz","custoso","cutuca","cutuca","cutucai","cutucam","cutucao","cutucar","cutucas",
		"cutuco","cutucou","dada","dadas","Dalila","danado","danando","danasse","dancado","daninha",
		"danosas","danosos","dardeja","dardeje","datado","datando","datasse","dataste","debalde","debanda",
		"debande","debitei","decada","decadas","decaida","decalca","decide","decidem","decides","decidi",
		"decidia","decidir","decidis","decidiu","decorre","decorro","dedada","dedadas","dedicai","dedilhe",
		"dedique","dedurar","dedure","dedurei","dedurem","dedures","dedurou","deduze","deduzem","deduzes",
		"deduziu","defasas","defases","defenda","defende","defende","defendi","defendo","deferir","defesas",
		"defumem","degrada","degrade","degreda","degreda","degrede","degredo","deicida","deidade","deitada",
		"deitei","deiteis","deixada","deixei","deixeis","delgada","delicie","delirei","demanda","demande",
		"demitem","demolem","demorem","denodo","dentada","denude","denudei","denudem","denudes","denudou",
		"deodoro","deparar","dependa","depende","depende","dependi","dependo","depilei","deponde","depondo",
		"derdes","derivei","derrama","derrame","derrapa","derrape","derreta","derrete","derrete","derreti",
		"derreto","derribe","derrogo","derrote","derroto","derrube","desabas","desabes","desanda","desande",
		"desatas","desates","desceis","desces","descrer","desde","desdize","desejas","desejes","desejos",
		"deserts","desfiei","desfies","desiste","desisti","desmede","desmedi","desnude","desosse","desosso",
		"desoves","despede","despedi","despes","despesa","despose","desposo","desse","dessem","desses",
		"destes","destoes","desunes","desviei","desvies","detecta","detecta","detecte","detecto","detende",
		"detendo","detento","detesta","detesta","deteste","detesto","deteta","deteta","detetai","detetam",
		"detetar","detetas","detete","detetei","detetem","detetes","deteto","detetou","deuses","devassa",
		"devasse","devedor","devendo","devesse","devolve","devolvo","diadema","difamai","difamam","diferir",
		"difundi","digerir","dilatai","diluiu","diodo","diodos","dioniso","Dioniso","dioxido","dirigir",
		"dirimam","dirimem","dirimir","discada","discais","dissipa","dissipa","dissipe","dissipo","distais",
		"disteis","ditada","ditadas","ditaria","ditosos","divagai","divida","dividam","dividas","divide",
		"dividem","divides","dividi","dividia","dividir","dividis","dividiu","divido","divisas","divises",
		"dizimam","dizimem","doada","doadas","doado","doador","doadora","doados","doando","dobrada",
		"dobrado","dobrara","doendo","doerdes","doeremo","doesse","doessem","doesses","doestes","doido",
		"doido","doidos","doidos","dolosas","dolosos","domada","domadas","domado","domador","domados",
		"domamo","domamos","domando","domaram","domarmo","domavam","domemo","domemos","dopada","dopadas",
		"dopado","dopados","dopando","dormido","dormimo","dorsos","dosado","dosamos","dosando","dosaras",
		"dosavas","dosemos","dotada","dotadas","dotado","dotados","dotando","dourada","dourado","dourara",
		"dourou","dragado","dragar","dragara","dragara","drenara","drogado","drogara","dublada","duende",
		"duendes","duodeno","durara","duraram","duraras","duraria","duvidai","duvidei","duvidou","ecoasse",
		"ecoemo","ecoemos","editei","editeis","educada","eduque","eduquei","eduquem","eduques","efetuou",
		"efusoes","egressa","egresso","ejetara","ejetava","elevada","elevara","elevava","elimine","elipses",
		"elogiei","emanam","emanamo","emanem","emanemo","embacam","embacem","embalam","embalem","embasam",
		"embasas","embasem","embases","embatam","embatem","embeba","embebam","embebas","embebe","embebe",
		"embebei","embebem","embeber","embebes","embebeu","embebi","embebia","embebo","emblema","emboaba",
		"embolem","embotem","embrome","embromo","emburre","emendam","emendem","emergem","emergir","emigrei",
		"emigrem","emitem","emitemo","emitiam","emitimo","empacam","empalam","empalem","empanam","empanem",
		"empapa","empapai","empapam","empapar","empapas","empape","empapei","empapem","empapes","empenam",
		"empenem","emperra","emperra","emperre","emperro","empinei","empinem","emplume","empocem","empolem",
		"empurre","emulem","emulemo","encanta","encante","encarar","encarna","encarne","encena","encena",
		"encenai","encenam","encenar","encenas","encene","encenei","encenem","encenes","enceno","encenou",
		"encerar","encerra","encerra","encerre","encerro","encimei","encimem","endosse","endosso","enervar",
		"enfiei","enfieis","engana","enganai","enganam","enganar","enganas","engane","enganei","enganem",
		"enganes","engasga","engenho","engessa","engessa","engesse","engesso","engomem","engrena","engrena",
		"engrene","engreno","enjoemo","enojemo","enredar","enrugue","ensacas","ensaiai","ensaias","ensaiei",
		"ensaies","enseada","ensebas","ensebes","ensejos","ensinai","ensinas","ensine","ensinei","ensinem",
		"ensines","ensopes","entanto","enteada","entenda","entende","entende","entendi","entendo","enterra",
		"enterra","enterre","enterro","entibie","entoemo","entorne","entorno","entorte","entorto","entrara",
		"entreta","entrete","entrete","entreti","entreto","enuncie","enviava","enviei","envieis","enviuve",
		"envolve","envolvo","enxugue","epiteto","epopeia","equipei","eregir","erguer","erguera","erguera",
		"ergueu","ericara","ericei","ericeis","erigir","erigira","erigira","erodemo","erodido","erosoes",
		"errada","erradas","erradia","errante","errara","erraram","erraras","errarei","errarem","errares",
		"erraria","errasse","erraste","errata","erratas","errava","erravam","erravas","erre","errei",
		"erreis","errem","erremo","erremos","erres","erronea","erroneo","esbarra","esbarre","esboces",
		"escadas","escalas","escales","escamas","escapas","escapes","escaras","escassa","escavas","escaves",
		"escoces","escoeis","escoemo","escoes","escopos","escorre","escorro","escoves","escuse","escusei",
		"escusem","escuses","escusou","escutes","esferas","esfoles","esfriei","esfries","esganas","esganes",
		"esgotes","esgotos","eslavas","esmagam","esmagas","esmeram","esmerar","esmeras","esmerem","esmeres",
		"esmeris","esmolem","esmoles","esmurre","esnobes","espacas","espaces","espadas","esparsa","esperar",
		"esperas","esperes","espessa","espesso","espetas","espetes","espetos","espiais","espiei","espieis",
		"espies","espioes","espirei","espires","espores","esporos","esposo","esposos","espumem","espumes",
		"esquiei","esquies","esse","estacas","estadas","estafas","estafes","estalas","estales","estante",
		"estares","estatal","estavas","esteios","estejas","estepes","estes","esteta","estetas","estimei",
		"estimem","estimes","estirei","estires","estofes","estojos","estrear","estudes","estufes","esvaeca",
		"esvaias","esvaias","europeu","evasiva","evitava","evitei","eviteis","evocava","evolve","evolvei",
		"evolvem","evolver","evolves","evolveu","evolvo","exagera","exarar","exarara","exarara","excesso",
		"excitei","excuses","execrar","exercer","exilei","exileis","eximem","eximemo","eximiam","eximimo",
		"existes","existis","exonero","expiei","expieis","expirei","exsudes","exumem","exumemo","faciais",
		"faiscai","faiscas","faiscas","falasse","faliria","falsas","familia","famosas","famosos","fardada",
		"fardado","farejar","farofa","farra","farrapo","farras","farreai","farrear","farreia","farreie",
		"farsas","fartar","fartara","fartara","fartura","fatiai","fatiais","fatigai","fatorar","faturar",
		"fedendo","fedesse","feiosos","ferirei","ferirem","ferires","feriria","ferisse","ferrara","ferrava",
		"ferre","ferrei","ferreis","ferrem","ferremo","ferres","ferroes","ferroso","ferver","fervera",
		"fervera","festoes","fiaria","fiariam","fiarias","ficaria","filaria","filiada","filial","filiara",
		"filiava","financa","firmara","fiscais","fisgais","fitaria","fixaria","fizesse","flagela","flagele",
		"flagrar","flanela","fofo","fofoca","fofoca","fofocai","fofocam","fofocar","fofocas","fofoco",
		"fofocou","fofoque","fofos","fogosas","fogosos","forcara","foreiro","forjara","formamo","formara",
		"formemo","forrado","forramo","forrara","forrava","forremo","forro","forros","forrou","foscos",
		"fosfato","fosforo","fosso","fossos","frasear","fratura","fraudar","freara","frearam","frearas",
		"frearei","frearem","freares","frearia","freasse","fremem","fresara","freseis","freses","fretara",
		"frieira","frigir","frigira","frigira","frisais","frisara","friseis","fritara","fruirei","fruiria",
		"fumaram","fumavam","fumegue","fundada","furara","furaram","furaras","furaria","furtara","gabasse",
		"gaga","gagas","gagueja","gagueje","galega","galegas","galga","galgado","galgai","galgais",
		"galgam","galgamo","galgar","galgara","galgara","galgas","galgava","ganiria","garagem","garfar",
		"garfara","garfara","gargalo","garoado","garoamo","garoar","garoara","garoara","garra","garrafa",
		"garras","garrida","gasosa","gasosas","gasoso","gasosos","gastais","gastas","geasse","geassem",
		"geasses","geastes","gelasse","gemem","gememo","gememos","gemeram","gemerem","gemermo","gemesse",
		"geneses","geologo","gerara","geraram","geraras","gerarei","gerarem","gerares","geraria","gerasse",
		"gerirei","gerirem","gerires","geriria","gerisse","giganta","gincana","gingai","gingais","gingara",
		"gingava","ginguei","girara","giraram","giraras","girarei","giraria","glacial","gongo","gongos",
		"gorara","goraram","gorarao","goraras","goraria","gorarmo","gorro","gorros","gostos","gostosa",
		"gostoso","gozosas","gozosos","graduar","grafar","grafara","grafara","grasnar","grasnas","gravar",
		"gravara","gravara","gravava","gravura","grifara","grilara","gritara","grosso","grossos","grudada",
		"grudara","guardar","guiaria","gulosos","habitai","habitat","hachura","haspas","haurira","herdada",
		"herdara","hesitei","hesites","higiene","honrara","horario","horror","icaria","icariam","icarias",
		"idosos","igualai","iguaria","ilharia","ilibada","iludida","iludido","iludiu","imagina","imantai",
		"imantam","imberbe","imergem","imergir","imigram","imigrar","imigrem","imitam","imitamo","imitara",
		"imitava","imitem","imitemo","imolamo","imolemo","impedem","impelem","imperei","imperem","impomo",
		"impomos","impormo","imprima","imprime","imprimi","imprimo","inalai","inalais","inativa","incense",
		"incisas","incisos","inclina","inclina","incline","inclino","incluiu","incorri","incorro","incutiu",
		"indagai","indexei","indiano","indigna","indigna","indigne","indigno","induziu","inebrie","infamai",
		"infamam","inferir","infinda","infindo","influiu","infundi","ingente","ingerir","injetei","inovava",
		"insana","insanas","insania","insanos","inseres","inserir","inseris","insinua","insinua","insinue",
		"insinuo","insiras","insista","insiste","insisti","insisto","insonia","insosso","instais","insteis",
		"intacta","inteire","intenta","intenta","intente","intento","interne","intimam","intimem","intuito",
		"intuiu","inundai","inundei","inundou","invadia","invejei","invente","ionizo","ionizou","irmanai",
		"irmanam","irmanar","ironizo","irradia","irradia","irradie","irradio","irreais","irriga","irriga",
		"irrigai","irrigam","irrigar","irrigas","irrigo","irrigou","irrigue","irrisao","irrita","irrita",
		"irritai","irritam","irritar","irritas","irrite","irritei","irritem","irrites","irrito","irritou",
		"irrompi","irrompo","isaias","isentei","isentes","isolais","isoleis","itarare","iterara","iterei",
		"itereis","jarra","jarras","jazesse","jejuara","jejuava","jejue","jejuei","jejueis","jejuem",
		"jejuemo","jejues","jejuou","jocosas","jocosos","joeirei","jorrado","jorramo","jorrara","jorrava",
		"jorremo","jorro","jorrou","jujuba","jurara","juraram","juraras","juraria","jururu","jururus",
		"karaoke","laborar","lacasse","lacrar","lacrara","lacrara","ladeada","ladeado","ladrado","ladrar",
		"ladrara","ladrara","laiciza","lamacal","lambam","lambamo","lambiam","laminai","laminam","lapela",
		"lapelas","lareira","largar","largara","largara","largura","lascais","lascas","latente","lateral",
		"latiria","laurear","lavasse","lavava","lavavam","lavavas","lavrar","lavrara","lavrara","lavrava",
		"legasse","legisle","legivel","leiloai","leiloe","leiloei","leiloem","leiloes","leiloes","lembrem",
		"leonino","lesaras","lesares","lesasse","lesaste","lesavas","leseis","lesemos","leses","lesoes",
		"lesse","lessem","lesses","lestes","levasse","levava","levavam","levavas","levitei","liberei",
		"lidaria","liderei","ligaria","lilases","limalha","limaram","limaria","limavam","limitam","limitem",
		"listais","listeis","litania","livrara","livrava","lixaria","lodacal","lodosas","lodosos","lograra",
		"loiola","louvava","louvou","lucrara","luxuoso","mancam","mancamo","mancham","mandada","mandado",
		"mandam","mandamo","maneamo","maneiam","maneiem","manejam","manejem","maninha","manjam","manjamo",
		"mansas","mapeamo","mapeiam","mapeiem","maquiai","maquiam","marasmo","marcam","marcamo","marcar",
		"marcara","marcara","marcham","marchar","marejam","marejar","marejem","marmita","marmore","marmota",
		"marrom","mascais","mascam","mascamo","mascas","massa","massape","massas","massiva","maturam",
		"maturar","matuta","matutai","matutam","matutar","matutas","matutem","matutou","maximal","medeiam",
		"medeiem","medem","mediei","medieis","mediemo","medirei","medirem","medisse","meditei","meditem",
		"medrara","medrem","medremo","meioses","melaram","melarem","melasse","melavam","melem","melemo",
		"melemos","melosos","memento","meneamo","meneara","meneava","meneiam","meneiem","meneses","mentem",
		"merecam","merecem","merecer","mesadas","mesclem","mescles","meses","mesmas","mesmice","mesmos",
		"mestres","metem","metemo","metemos","meteoro","meteram","meterem","metermo","metesse","meteste",
		"mexem","mexemo","mexemos","mexeram","mexerem","mexermo","mexesse","miaram","miaria","miariam",
		"miarias","miassem","miavam","migrara","militam","militem","minaram","minaria","minavam","mirara",
		"miraram","miraras","mirarei","mirarem","miraria","mirarmo","miravam","mirrada","missiva","mitigam",
		"mixaria","moamo","moamos","mobilio","mocambo","modelem","moderem","modismo","modorra","modulou",
		"moemo","moemos","moerem","moeremo","moermo","moermos","moesse","moessem","moesses","moestes",
		"mofamo","mofamos","mofaram","mofarmo","mofavam","mofemo","mofemos","moiamos","moldada","moldado",
		"moldamo","moldemo","molhamo","molhemo","momento","momo","momos","montamo","montemo","morador",
		"moramo","moramos","morara","moraram","morarao","moraras","morarem","moraria","morarmo","moravam",
		"mordamo","mordemo","mordido","mordomo","moremo","moremos","mormaco","morosas","morosos","morram",
		"morramo","morrem","morremo","morriam","morrido","morro","morros","moscamo","movamo","movamos",
		"movemo","movemos","moverem","movermo","movesse","muamba","muambas","mudada","mudadas","mudaram",
		"mudavam","mundana","murara","muraram","muraras","murarem","muraria","murarmo","muravam","murmura",
		"murmura","murmure","murmuro","museus","musquem","musques","nababo","nababos","nadado","nadando",
		"nadasse","namoram","namorar","narina","narinas","narra","narrada","narrado","narrai","narrais",
		"narram","narramo","narrar","narrara","narrara","narras","narrava","nasais","nascais","nascas",
		"nascias","nefanda","negasse","nesse","esses","nestes","nevasse","nevava","nevavam","nevavas",
		"ninhada","nitrito","nivelei","nodosas","nodosos","noivava","nomeamo","nomeiem","nonato","nono",
		"nosso","nossos","notando","noticio","noturno","novicio","numerem","obceco","obcecou","obedeco",
		"obreiro","obturou","obtusos","obviava","ociosas","ociosos","ocorra","ocorram","ocorras","ocorre",
		"ocorre","ocorrei","ocorrem","ocorrer","ocorres","ocorreu","ocorri","ocorria","ocorro","ocultou",
		"ocupou","ofereco","oficio","oficiou","ofuscou","oleosas","oleosos","omissao","omisso","omissos",
		"omitemo","omitiam","omitido","omitimo","ondeada","ondeado","ondulou","onerara","oneremo","operara",
		"operemo","opiniao","opostas","opostos","oprimir","orador","oradora","orara","oraram","orarao",
		"oraras","oraremo","oraria","orariam","orarias","orarmo","orarmos","orcara","orcaram","orcarao",
		"orcaras","orcaria","orcarmo","ordeiro","origino","orlara","orlaram","orlarao","orlaras","orlaria",
		"orlarmo","ornando","ornara","ornaram","orarao","ornaras","ornaria","ornarmo","osculou","ossada",
		"ossadas","ossinho","osso","ossos","ossudo","ossudos","ostente","ostento","otimizo","otomana",
		"ousadas","ousados","ousamos","ousaras","ousavas","ousemos","ousou","outrora","outubro","ovalado",
		"oxalato","oxidada","oxidado","pagasse","paginai","pairai","pairais","pairar","pairara","pairara",
		"palitai","palpita","pampa","pampas","parar","parara","parara","pararam","pararao","pararas",
		"pararas","pararei","pararem","parares","pararia","pararmo","parasse","parear","pareara","pareara",
		"parecer","parira","pariram","pariras","parirei","pariria","partira","pasmais","pasmam","pasmamo",
		"pasmas","passa","passada","passado","passai","passais","passam","passamo","passar","passara",
		"passara","passas","passava","passeai","passear","passeia","passeie","passiva","pastais","pastas",
		"pastosa","pastoso","patente","patinai","pausas","pecasse","pedirei","pedisse","pedrada","pegasse",
		"peitei","peiteis","pelasse","penasse","penosos","penseis","penses","pensoes","perder","perdera",
		"perdera","perdure","perecer","pereira","perfure","pericie","pesadas","pesaras","pesares","pesasse",
		"pesaste","pesavas","peseis","pesemos","peses","pesetas","pesques","pestes","piaria","piariam",
		"piarias","picaria","piedade","pifaria","piorara","pipocai","pipoco","pipocou","pirraca","pisadas",
		"pisais","pisaras","pisaria","pisavas","piscais","piseis","plagiai","plasmam","plasmas","podada",
		"podadas","podado","podados","podando","podendo","podido","policio","pomposa","pomposo","pontuou",
		"porosas","porosos","portara","posamos","posaras","posavas","posemos","pospoes","pospomo","pospor",
		"pospora","pospos","pospus","possamo","posso","possuiu","possuo","postos","potassa","potente",
		"poupada","poupado","poupamo","poupara","poupava","poupemo","poupo","poupou","pousos","pousou",
		"povoada","povoara","povoava","precoce","prefere","preferi","pregara","premem","prememo","premiei",
		"premiem","prender","prenses","prepara","prepara","prepare","preparo","prepoe","prepoem","prepoes",
		"prepomo","prepor","prepora","prestes","pretere","preteri","prever","prevera","prezara","primara",
		"privara","privava","procrio","procuro","profere","profiro","proibir","propaga","propago","propala",
		"propalo","propomo","propor","propora","propria","proprio","prostro","provara","provava","pulula",
		"pulula","pululai","pululam","pulular","pululas","pulule","pululei","pululem","pulules","pululo",
		"pululou","purgara","purpura","queimei","queimem","queixei","querer","querera","rachar","rachara",
		"rachara","raciais","radar","radares","radiado","radiai","radiais","radiar","radiara","radiara",
		"radicai","radicar","raiai","raiais","raiar","raiara","raiara","raiaram","raiarao","raiaras",
		"raiaras","raiarei","raiarem","raiares","raiaria","raiarmo","raiasse","rajar","rajara","rajara",
		"rajaram","rajarao","rajaras","rajaras","rajarei","rajarem","rajares","rajaria","rajarmo","rajasse",
		"ralar","ralara","ralara","ralaram","ralarao","ralaras","ralaras","ralarei","ralarem","ralares",
		"ralaria","ralarmo","ralasse","ralhar","ralhara","ralhara","ramagem","rangera","ranhura","raposas",
		"raposos","rara","raras","rareado","rareai","rareais","rareamo","rarear","rareara","rareara",
		"rareava","rarefaz","rarefez","rareia","rareiam","rareias","rareie","rareiem","rareies","rasas",
		"rasgais","rasgar","rasgara","rasgara","rasgas","raspais","raspar","raspara","raspara","raspas",
		"rastros","rasura","rasurai","rasuram","rasurar","rasuras","rasures","rasurou","ratear","rateara",
		"rateara","reabra","reabram","reabras","reabre","reabrem","reabres","reabria","reagira","realcar",
		"realeza","reatar","reatara","reatara","reaver","reavera","reaviva","reavive","rebarba","rebater",
		"rebelar","rebitei","reboara","reboemo","recaira","recalca","recarga","recear","receara","receara",
		"receava","receber","receoso","recesso","rechace","rechear","recitei","recobre","recobro","recorde",
		"recordo","recorre","recorro","recorte","recorto","recrea","recreai","recrear","recreia","recreie",
		"recreio","recreou","recriai","recrie","recriei","recriem","recries","recrute","recuara","recuses",
		"redigir","redimem","redimir","redobre","redobro","redondo","redores","redunde","reentra","refarei",
		"refaria","refazer","refere","referem","referes","referi","referia","referir","referis","referiu",
		"referva","referve","referve","refervi","refervo","refinei","refizer","reforce","reforco","reforme",
		"reformo","refrata","refrate","refrea","refreai","refrear","refrega","refrega","refrego","refreia",
		"refreie","refreio","refreou","refroes","regalar","regara","regaram","regaras","regarei","regarem",
		"regares","regaria","regasse","reger","regera","regera","regerai","regeram","regerao","regerar",
		"regeras","regeras","regere","regerei","regerem","regeres","regeria","regermo","regero","regerou",
		"regesse","regrara","regrava","regrave","regre","regredi","regrei","regreis","regrem","regremo",
		"regres","regride","reinara","reinei","reineis","reitera","reitera","reitere","reitero","relatar",
		"relaxar","relegar","reler","relera","relera","releram","relerao","releras","releras","relerei",
		"relerem","releres","releria","relermo","relesse","remara","remaram","remaras","remarca","remarei",
		"remarem","remares","remaria","remarmo","remasse","rematam","rematar","rematem","remavam","remem",
		"rememo","rememos","remessa","remetam","remetem","remeter","remexam","remexem","remexer","remiram",
		"remirei","remirem","remires","remiria","remirmo","remisse","remoamo","remocem","remoem","remoemo",
		"remoer","remoera","remoera","remorso","removem","remover","rendada","render","rendera","rendera",
		"renegar","reouver","repara","reparai","reparam","reparar","reparas","repare","reparei","reparem",
		"repares","reparta","reparte","repassa","repasse","repelir","repetir","reporao","reporei","reporem",
		"repores","repormo","reporte","reporto","repovoe","represa","represa","represe","represo","reprime",
		"reprimi","reprise","reprobo","reprove","reprovo","repuser","requer","requere","requero","reserva",
		"reserva","reserve","reservo","reses","resfrie","resides","residir","residis","resiste","resisti",
		"respire","ressaca","ressoar","ressoe","ressoei","ressoem","ressoes","restara","resteis","restes",
		"resumem","resumes","retarda","retarde","reter","retera","reterao","reteras","reterei","reterem",
		"reteres","reteria","retesar","retesas","reteses","retinir","retirai","retire","retirei","retirem",
		"retires","retiver","retomem","retorce","retorco","retorne","retorno","retraca","retrace","retraem",
		"retraia","retraia","retrata","retrata","retrate","retrato","revelar","rever","revera","reverao",
		"reveras","reverei","reverem","reveres","reveria","reversa","reverso","reverta","reverte","reverte",
		"reverti","reverto","reveses","revezar","revidei","revirai","revire","revirei","revirem","revires",
		"revisei","revises","revisse","revive","revivei","revivem","reviver","revives","reviveu","revivi",
		"revivia","revolve","revolvo","rezara","rezaram","rezaras","rezarei","rezarem","rezares","rezaria",
		"rezasse","ribeiro","ribombo","rifara","rifaram","rifaras","rifarei","rifaria","rimara","rimaram",
		"rimaras","rimarei","rimarem","rimaria","rimarmo","rimavam","rirei","rireis","riria","ririam",
		"ririas","ririeis","risadas","riscais","riscara","roberio","roberto","rocara","rocaram","rocarao",
		"rocaras","rocaria","rocarmo","roceiro","rodada","rodadas","rodado","rodados","rodando","rodara",
		"rodaram","rodarao","rodaras","rodaria","rodarmo","rodeada","rodeado","rodeara","roedor","roerao",
		"roerdes","roerei","roereis","roerem","roeremo","roeres","roermo","roermos","roesse","roessem",
		"roesses","roestes","rogara","rogaram","rogarao","rogaras","rogaria","rogarmo","rolara","rolaram",
		"rolarao","rolaras","rolaria","rolarmo","romaria","romeiro","rompamo","rompemo","roncara","rondado",
		"rondara","rosadas","rosados","rosario","rosnara","rostos","roteara","roteiro","rotulou","rufara",
		"rufaram","rufaras","rufaria","rugara","rugaram","rugaras","rugaria","rugirei","rugiria","rugosos",
		"ruirei","ruireis","ruiria","ruiriam","ruirias","rumara","rumaram","rumaras","rumarem","rumaria",
		"rumarmo","rumavam","ruptura","saberes","sabias","sabidas","sacadas","sacados","sacais","sacamos",
		"sacaras","sacaras","sacares","sacas","sacasse","sacaste","sacavas","saciai","saciais","sacias",
		"sacieis","sacolas","sacras","sacudas","sadias","safais","safamos","safaras","safaras","safares",
		"safas","safasse","safaste","safavas","safiras","safras","sagas","sagazes","sagrais","sagrar",
		"sagrara","sagrara","sagras","saiais","saiamos","saiamos","saias","saias","saibais","saibas",
		"saidas","sairas","saireis","sairia","sairiam","sairias","saladas","salas","saldada","saldado",
		"saldais","saldas","saletas","salgais","salgas","salinas","salivai","salivas","salsa","saltais",
		"saltas","saltita","salvais","salvas","salvava","sambais","sambam","sambamo","sambas","sanais",
		"sanamos","sanando","sanaras","sanaras","sanares","sanas","sanasse","sanaste","sanavas","saneais",
		"saneias","saneies","sanfona","sangrar","sangras","santana","santas","sapatas","sapatos","sapecas",
		"sarais","saramos","sarar","sarara","sarara","sararam","sararao","sararas","sararas","sararei",
		"sararem","sarares","sararia","sararmo","saras","sarasse","saraste","saravas","sarcas","sardas",
		"sarrafo","saturar","saturas","saudade","saudado","saudais","saudas","saudosa","saudoso","saunas",
		"sauvas","savanas","sazonas","searas","sebes","seboso","sebosos","secaras","secares","secasse",
		"secaste","secavas","secoes","sedes","sediada","sediais","sediei","sedieis","sedies","sedoso",
		"sedosos","seduzes","segrega","segrega","segrego","segues","segures","seladas","selaras","selares",
		"selasse","selaste","selavas","seleis","selemos","seles","seletas","seletos","semanas","semeada",
		"semeais","semeamo","semeara","semeava","semeiam","semeias","semeiem","semeies","senoes","sensata",
		"senteis","sentes","separar","separas","separes","sequeis","seques","serdes","sereias","sereis",
		"seremos","serenar","serenas","serenes","serenos","seres","seresta","seriais","seriara","seriei",
		"serieis","serieis","series","sermoes","serpear","serrada","serrais","serrana","serrara","serras",
		"serrava","serre","serrei","serreis","serrem","serremo","serres","serrote","sertoes","serves",
		"serzes","sessoes","setenta","setores","severas","severos","sexteto","sibilas","sibiles","sibilos",
		"sigais","silabas","silvais","silvava","silveis","sinais","sinodos","sintais","sintese","sinuoso",
		"sirenes","siris","sirvais","sirzais","sismai","sismais","sismam","sismamo","sismara","sismava",
		"sismei","sismeis","sismem","sismemo","sitiada","sitiais","sitiara","sitias","sitiava","sitieis",
		"sities","situais","situeis","soalhos","soamos","soaras","soarias","soarmos","soavas","sobejos",
		"soberbo","socadas","socados","socamos","socaras","socavas","sociais","socorra","socorre","socorre",
		"socorri","socorro","socos","soemos","sofismo","sogros","solamos","solapas","solaras","solavas",
		"soldada","soldado","soldos","solemos","solenes","solos","soltos","solucos","solucou","somadas",
		"somados","somamo","somamos","somaram","somaras","somarmo","somavam","somavas","somemo","somemos",
		"somenos","somos","sonatas","sondada","sondado","sonetos","sonhos","sonoras","sonoros","sonos",
		"sopapo","sopapos","soprara","soros","sorrias","sorrido","sorrimo","sorrio","sorris","sorriso",
		"soslaio","sossego","sovacos","sovadas","sovados","sovamos","sovaras","sovava","sovavam","sovavas",
		"sovemos","status","suadas","suaras","suarias","suavas","subsolo","sucatas","sucedes","sucedeu",
		"sudeste","sufocou","sugadas","sugaras","sugavas","sugeres","sugueis","sugues","sujaras","sujavas",
		"sulques","sumamos","sumimos","superes","supomos","suposto","supurar","supuras","supures","sustara",
		"sustava","susteu","sustou","suturar","suturas","sutures","tacasse","tacaste","tampam","tampamo",
		"tanta","tantas","tapasse","tapaste","tapete","tapetes","tardado","tardar","tardara","tardara",
		"tarifai","tarifar","tarraxa","tartaro","tateado","tateai","tateais","tateamo","tatear","tateara",
		"tateara","tateava","tateia","tateiam","tateias","tateie","tateiem","tateies","tatua","tatuado",
		"tatuai","tatuais","tatuam","tatuamo","tatuar","tatuara","tatuara","tatuas","tatuava","tatuou",
		"taubate","taxasse","taxaste","taxista","teatral","tecesse","teceste","teimei","teimeis","teimem",
		"teimemo","temem","tememo","tememos","temeram","temerem","temermo","temesse","temeste","tenente",
		"tensoes","tentada","tentara","tentava","tente","tentei","tenteis","tentem","tentemo","tentes",
		"terrena","terreno","terroso","teses","testada","testais","testara","testas","testava","teste",
		"testei","testeis","testem","testemo","testes","teteia","teteias","tilinta","tilinta","tilinte",
		"tilinto","tinindo","tinisse","tiniste","tirania","tirara","tiraram","tiraras","tirarei","tiraria",
		"tirita","tirita","tiritai","tiritam","tiritar","tiritas","tirite","tiritei","tiritem","tirites",
		"tirito","tiritou","titanio","titere","titeres","titias","titicas","titios","tivesse","tiveste",
		"toalete","tocaiai","tocata","tocatas","tomamo","tomamos","tomaram","tomarmo","tomavam","tombamo",
		"tombemo","tomemo","tomemos","tomento","topete","topetes","tornara","torrada","torrado","torramo",
		"torrao","torrara","torrava","torremo","torro","torrou","tortura","tortura","torture","torturo",
		"tosamos","tosaras","tosaste","tosavas","tosemos","tossido","tossimo","tostado","tostais","tostamo",
		"tostao","tostara","tostas","tostava","tosteis","tostemo","tostes","tosto","tostoes","tostou",
		"toureou","tracar","tracara","tracara","tragar","tragara","tragara","traiais","traira","trairam",
		"trairas","trairei","trairia","trajar","trajara","trajara","tramita","trancar","trancar","transar",
		"transas","traria","trariam","trarias","trastes","trata","tratada","tratado","tratai","tratais",
		"tratam","tratamo","tratar","tratara","tratara","tratas","tratava","trator","travar","travara",
		"travara","travava","treinei","tremem","trememo","tremer","tremera","tremera","trepara","tresler",
		"tricoto","tristes","tritura","tritura","triture","trituro","trocara","trocara","trotado","trotamo",
		"trotar","trotara","trotara","trotava","trotear","troteie","troteio","trotemo","troteou","troto",
		"trotou","trustes","tumulto","turbara","turvara","turvava","tutele","tutelei","tutelem","tuteles",
		"tutelou","uisques","uivaria","uivava","uivavam","uivavas","ulula","ulula","ululado","ululai",
		"ululais","ululam","ululamo","ulular","ululara","ululara","ululas","ululava","ulule","ululei",
		"ululeis","ululem","ululemo","ulules","ululo","ululou","urdirei","urdiria","ureter","urgirei",
		"urgiria","urinara","urrara","urraram","urraras","urraria","urrasse","urrava","urravam","urravas",
		"urrou","ursadas","usadas","usaras","usarias","usavas","usuais","usuras","usurpar","usurpas",
		"usurpes","vacilai","vacinai","vadeado","vadeava","vadiado","vadiai","vadiais","vadiava","vagasse",
		"vagava","vagavam","vagavas","vagiria","vaiai","vaiais","vaiarei","vaiaria","vaiasse","vaiava",
		"vaiavam","vaiavas","vaidade","valesse","validai","valsas","valvula","varar","varara","varara",
		"vararam","vararao","vararas","vararas","vararei","vararem","varares","vararia","vararmo","varasse",
		"varava","varavam","varavas","varejar","variai","variais","variar","variara","variara","variava",
		"varra","varrais","varram","varramo","varras","varrera","varria","varriam","varrias","varrida",
		"vassalo","vastas","vazasse","vazava","vazavam","vazavas","vedada","vedadas","vedasse","vedava",
		"vedavam","vedavas","velasse","velava","velavam","velavas","vendada","vendava","veneno","venenos",
		"venerar","venosos","ventava","verdade","versara","versava","verseis","verses","versoes","verter",
		"vertera","vertera","vestes","vetasse","vetaste","vetava","vetavam","vetavas","viajai","viajais",
		"viajava","viaveis","vibrara","vibrava","vicejei","viciada","viciara","viciava","vicioso","vicosos",
		"vidrada","vidrara","vidrava","viesse","viessem","viesses","viestes","vigiara","vigiava","vilania",
		"vincava","vingava","violino","virara","viraram","viraras","virarei","viraria","virava","viravam",
		"viravas","visadas","visais","visaras","visaria","visava","visavam","visavas","viscoso","viseis",
		"visitas","visites","vistais","vistoso","visuais","vitimam","vitimem","viuvai","viuvais","viuvara",
		"viuvava","viuvei","viuveis","viuvou","vivais","vivei","viveiro","viveis","vivente","vivere",
		"viverei","viverem","viveres","viveres","viveria","vivesse","viveste","vivi","vivia","viviam",
		"vivias","vivida","vividas","vivido","vividos","vivieis","vivinha","vivinho","voadora","voava",
		"voavam","voavas","voltava","volvamo","volvemo","volvido","volvo","vosso","vossos","votava",
		"votavam","votavas","votivo","votivos","xeretar","zabumba","zanza","zanzado","zanzai","zanzais",
		"zanzam","zanzamo","zanzar","zanzara","zanzara","zanzas","zanzava","zarpar","zarpara","zarpara",
		"zelasse","zelosos","zerara","zeraram","zeraras","zerarei","zerarem","zerares","zeraria","zerasse",
		"zonzo","zonzos","zunzum","zunzuns","zurrara","zurrava","zurrou"
	};
	
	public static String getPalavra()
	{
		Random rand=new Random();
		int index=rand.nextInt(palavras.length);
		return palavras[index];
	}
	
    public static String removerAcentos(String palavra) {
        String normalizada = Normalizer.normalize(palavra, Normalizer.Form.NFD);
        Pattern pattern = Pattern.compile("\\p{InCombiningDiacriticalMarks}+");
        return pattern.matcher(normalizada).replaceAll("");
    }
	
	public static void main(String[] args)
	{
		
//		String caminhoArquivo = "src\\main\\webapp\\files\\palavras.txt";
//		List<String> list=new ArrayList<String>();
//
//        try (BufferedReader br = new BufferedReader(new FileReader(caminhoArquivo)))
//        {
//            String p1;
//            while ((p1 = br.readLine()) != null) 
//            {
////            	p1=removerAcentos(p1);
//    			if(p1.length()<8&&AuxCombinacao.contarRepeticao(p1)>1)
//    				list.add(p1);
//    			else
//    			{
//    			}
//            }
//        } catch (IOException e) {
//        }
//        
		String palavras[] = TextoAnagramas.palavras;
		List<String> list=new ArrayList<String>();

		for(int i = 0; i < palavras.length; i++)
		{
			String p1 = palavras[i];
			p1=removerAcentos(p1);	

			if(p1.length()<8&&AuxCombinacao.contarRepeticao(p1)>0)
				list.add(p1);
		}
		
//		remove palavras repetidas
		for(int i = 0; i < palavras.length; i++)
		{
			String p1 = palavras[i];
			for(int j = i+1; j < palavras.length; j++)
			{
				String p2 = palavras[j];
				if(p1.equals(p2))
				{
					list.remove(p1);
					break;
				}
			}
		}
		
//		remove vogais repetidas
		for(int i = 0; i < palavras.length; i++)
		{
			String palavra=palavras[i];
			for(int j = 0; j < palavra.length()-1; j++)
			{
				char a=palavra.charAt(j);
				char b=palavra.charAt(j+1);

				if(a==b&&(a=='a'||a=='e'||a=='i'||a=='o'||a=='u'))
				{
					list.remove(palavra);
					break;
				}
				
			}
		}
	}
	
}
